import type { CultureChallenge, CultureContent, CultureLanguage, CultureTranslation, LanguageLesson, LessonDetail } from './culture.types';
const content = (id: string, type: CultureContent['type'], slug: string, language: string, region: string, communityName: string): CultureContent => ({ id, type, slug, status: 'PUBLISHED', visibility: 'PUBLIC', primaryLanguageCode: language, countryCode: 'CM', adminLevel1Id: region, cityId: null, communityName, sourceType: 'COMMUNITY', verificationStatus: 'VERIFIED', sensitivityLevel: 'PUBLIC', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-08-01T00:00:00Z', publishedAt: '2026-01-01T00:00:00Z' });
export const demoCultureContents: CultureContent[] = [
  content('culture-1', 'PROVERB', 'la-patience-construit', 'bas', 'CENTRE', 'Bassa'), content('culture-2', 'STORY', 'la-legende-du-mont-cameroun', 'baf', 'SUD-OUEST', 'Bakweri'), content('culture-3', 'RECIPE', 'ndole-familial', 'dua', 'LITTORAL', 'Sawa'), content('culture-4', 'DANCE', 'danse-bottle-dance', 'mgo', 'NORD-OUEST', 'Grassfields'), content('culture-5', 'TRADITION', 'ngouon-foumban', 'bax', 'OUEST', 'Bamoun'), content('culture-6', 'ORAL_HISTORY', 'memoire-des-lamidos', 'ff', 'NORD', 'Peul'), content('culture-7', 'SONG', 'chants-de-pirogue', 'dua', 'LITTORAL', 'Sawa'), content('culture-8', 'SYMBOL', 'symboles-toghu', 'mgo', 'NORD-OUEST', 'Bamenda'), content('culture-9', 'EXPRESSION', 'saluer-en-ewondo', 'ewo', 'CENTRE', 'Ewondo'), content('culture-10', 'HISTORICAL_FIGURE', 'reines-mères-des-grassfields', 'fr', 'OUEST', 'Bamiléké'),
];
export const demoCultureTranslations: CultureTranslation[] = demoCultureContents.map((item, index) => ({ id: `translation-${item.id}`, languageCode: 'fr', title: item.slug.replace(/-/g, ' '), summary: `Contenu culturel vérifié n°${index + 1}.`, body: 'Une transmission communautaire documentée, racontée et préservée avec le consentement de ses contributeurs.', translatorId: 'demo-user', status: 'VERIFIED', createdAt: '2026-01-01T00:00:00Z' }));
export const demoLanguages: CultureLanguage[] = [
  ['bas', 'Bassa', 'Basaá', 'Langue du peuple Bassa.'], ['dua', 'Douala', 'Duala', 'Langue Sawa parlée sur le littoral.'], ['ewo', 'Ewondo', 'Ewondo', 'Langue largement parlée autour de Yaoundé.'], ['ff', 'Fulfulde', 'Fulfulde', 'Langue véhiculaire du Nord Cameroun.'], ['bax', 'Bamoun', 'Shüpamom', 'Langue du royaume Bamoun.'], ['mgo', 'Metaʼ', 'Mətaʼ', 'Langue des Grassfields.'], ['baf', 'Bafaw', 'Bafaw', 'Langue du Sud-Ouest.'], ['bul', 'Bulu', 'Bulu', 'Langue du sud forestier.'], ['ken', 'Kenyang', 'Kenyang', 'Langue du Sud-Ouest camerounais.'], ['yba', 'Yemba', 'Yemba', 'Langue parlée autour de Dschang.'],
].map(([code, name, nativeName, description]) => ({ code, name, nativeName, countryCodes: ['CM'], writingSystem: 'Latin', status: 'ACTIVE', description, speakerEstimate: null, verified: true }));
export const demoLessons: LanguageLesson[] = demoLanguages.flatMap((language, languageIndex) => [
  { id: `lesson-${language.code}-1`, languageCode: language.code, topicId: null, title: `Saluer en ${language.name}`, description: 'Les salutations essentielles.', difficulty: 1, estimatedMinutes: 4, status: 'PUBLISHED', displayOrder: languageIndex * 2 + 1 },
  { id: `lesson-${language.code}-2`, languageCode: language.code, topicId: null, title: `Se présenter en ${language.name}`, description: 'Nom, origine et formules de politesse.', difficulty: 2, estimatedMinutes: 7, status: 'PUBLISHED', displayOrder: languageIndex * 2 + 2 },
]);
const phraseSets: Record<string, [string, string, string][]> = {
  bas: [['Mbolo','Bonjour','m-bo-lo'],['Me yé','Merci','mé-yé'],['A nde?','Comment allez-vous ?','a-ndé']],
  dua: [['Mbolo','Bonjour','m-bo-lo'],['Na som','Merci','na-som'],['O si?','Comment vas-tu ?','o-si']],
  ewo: [['Mbolo','Bonjour','m-bo-lo'],['Akiba','Merci','a-ki-ba'],['O ne va?','Comment vas-tu ?','o-né-va']],
};
export const demoLessonDetails: LessonDetail[] = demoLessons.map((lesson) => {
  const phrases = phraseSets[lesson.languageCode] ?? [['Mbolo','Bonjour','m-bo-lo'],['Merci','Merci','mer-si'],['Bénédiction','Bienvenue','bien-ve-nu']];
  return { lesson, items: phrases.map(([phrase,translation,phonetic],index)=>({id:`${lesson.id}-item-${index+1}`,phrase,translation,transcription:phonetic,phonetic,audioMediaId:'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',imageMediaId:null,culturalContext:'Formule de démonstration à valider avec un locuteur ou une locutrice de la communauté.',difficulty:lesson.difficulty,examples:null,displayOrder:index+1})), exercises: phrases.map(([phrase,translation],index)=>({id:`${lesson.id}-exercise-${index+1}`,type:'MULTIPLE_CHOICE',prompt:`Quelle est la traduction de « ${phrase} » ?`,optionsJson:JSON.stringify([translation,'Au revoir','Bienvenue','Bonne nuit']),displayOrder:index+1})) };
});
export const demoChallenges: CultureChallenge[] = [
  { id: 'challenge-1', title: 'Un mot de chez vous', description: 'Partagez un mot à transmettre.', type: 'CONTRIBUTION', countryCode: 'CM', languageCode: null, startsAt: '2026-01-01T00:00:00Z', endsAt: '2026-12-31T00:00:00Z', status: 'ACTIVE', rewardDefinitionId: null, moderationRequired: true, prompts: ['Quel mot souhaitez-vous transmettre ?'] },
  { id: 'challenge-2', title: 'Une recette, une histoire', description: 'Documentez une recette familiale.', type: 'CONTRIBUTION', countryCode: 'CM', languageCode: null, startsAt: '2026-06-01T00:00:00Z', endsAt: '2026-10-31T00:00:00Z', status: 'ACTIVE', rewardDefinitionId: null, moderationRequired: true, prompts: ['Qui vous a transmis cette recette ?'] },
  { id: 'challenge-3', title: 'Parlez votre langue', description: 'Enregistrez une salutation locale.', type: 'CONTRIBUTION', countryCode: 'CM', languageCode: 'bas', startsAt: '2026-07-01T00:00:00Z', endsAt: '2026-11-30T00:00:00Z', status: 'ACTIVE', rewardDefinitionId: null, moderationRequired: true, prompts: ['Comment salue-t-on chez vous ?'] },
];
