import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuthStore } from '@/features/auth/auth.store';
import { useCountryStore } from '@/features/country/country.store';
import { createIdempotencyKey, toSpringPage } from '@/services/api/contracts';
import { cultureApi } from './culture.api';
import { demoChallenges, demoCultureContents, demoCultureTranslations, demoLanguages, demoLessons } from './culture.demo';
import { cultureKeys } from './culture.query-keys';
import type { CultureFilters } from './culture.types';

const useDemoMode = () => useAuthStore((state) => state.sessionMode?.startsWith('demo-') ?? false);
export function useCultureContents(filters: CultureFilters = {}) { const demo = useDemoMode(); return useQuery({ queryKey: cultureKeys.contents(filters), queryFn: () => demo ? Promise.resolve(toSpringPage(demoCultureContents)) : cultureApi.listContents(filters) }); }
export function useCultureContent(id?: string) { const demo = useDemoMode(); return useQuery({ queryKey: cultureKeys.content(id ?? ''), enabled: Boolean(id), queryFn: () => demo ? Promise.resolve({ content: demoCultureContents[0], translations: demoCultureTranslations }) : cultureApi.getContent(id!) }); }
export function useCultureLanguages() { const demo = useDemoMode(); return useQuery({ queryKey: cultureKeys.languages(), queryFn: () => demo ? Promise.resolve(demoLanguages) : cultureApi.languages() }); }
export function useLanguage(code?: string) { const demo = useDemoMode(); return useQuery({ queryKey: cultureKeys.language(code ?? ''), enabled: Boolean(code), queryFn: () => demo ? Promise.resolve(demoLanguages[0]) : cultureApi.language(code!) }); }
export function useLanguageLessons(code?: string) { const demo = useDemoMode(); return useQuery({ queryKey: cultureKeys.lessons(code ?? ''), enabled: Boolean(code), queryFn: () => demo ? Promise.resolve(demoLessons) : cultureApi.lessons(code!) }); }
export function useLesson(id?: string) { const demo = useDemoMode(); return useQuery({ queryKey: cultureKeys.lesson(id ?? ''), enabled: Boolean(id), queryFn: () => demo ? Promise.resolve({ lesson: demoLessons[0], items: [], exercises: [] }) : cultureApi.lesson(id!) }); }
export function useLanguageProgress(code?: string) { const demo = useDemoMode(); return useQuery({ queryKey: cultureKeys.progress(code), queryFn: () => demo ? Promise.resolve([]) : cultureApi.progress(code) }); }
export function useDailyWord() { const demo = useDemoMode(); const countryCode = useCountryStore((state) => state.selectedCountryCode ?? 'CM'); const languageCode = useCountryStore((state) => state.preferredLanguageCode); return useQuery({ queryKey: [...cultureKeys.all, 'daily-word', countryCode, languageCode], queryFn: () => demo ? Promise.resolve(demoCultureContents[0]) : cultureApi.dailyWord(countryCode, languageCode) }); }
export function useChallenges() { const demo = useDemoMode(); return useQuery({ queryKey: cultureKeys.challenges(), queryFn: () => demo ? Promise.resolve(toSpringPage(demoChallenges)) : cultureApi.challenges() }); }
export function useChallenge(id?: string) { const demo = useDemoMode(); return useQuery({ queryKey: cultureKeys.challenge(id ?? ''), enabled: Boolean(id), queryFn: () => demo ? Promise.resolve(demoChallenges[0]) : cultureApi.challenge(id!) }); }
export function useCompleteLesson() { const client = useQueryClient(); const demo = useDemoMode(); return useMutation({ mutationFn: ({ id, score }: { id: string; score: number }) => demo ? Promise.resolve({ id: `demo-progress-${id}`, userId: 'demo-user', languageCode: 'bas', lessonId: id, startedAt: new Date().toISOString(), completedAt: new Date().toISOString(), score, attemptCount: 1 }) : cultureApi.completeLesson(id, score, createIdempotencyKey()), onSuccess: () => client.invalidateQueries({ queryKey: cultureKeys.progress() }) }); }
export function useStartLesson() { const demo = useDemoMode(); return useMutation({ mutationFn: (id: string) => demo ? Promise.resolve({ id: `demo-progress-${id}`, userId: 'demo-user', languageCode: 'bas', lessonId: id, startedAt: new Date().toISOString(), completedAt: null, score: null, attemptCount: 0 }) : cultureApi.startLesson(id) }); }
export function useSubmitLessonAttempt() { const demo = useDemoMode(); return useMutation({ mutationFn: ({ id, exerciseId, answerText, mediaId }: { id: string; exerciseId: string; answerText?: string; mediaId?: string }) => demo ? Promise.resolve({ attemptId: `demo-attempt-${exerciseId}`, correct: null, manualReviewRequired: false }) : cultureApi.submitAttempt(id, { exerciseId, answerText, mediaId }) }); }
export function useCreateCultureContribution() { const demo = useDemoMode(); const client = useQueryClient(); return useMutation({ mutationFn: (input: import('./culture.types').CultureContributionInput) => demo ? Promise.resolve(demoCultureContents[0]) : cultureApi.createContribution(input), onSuccess: () => client.invalidateQueries({ queryKey: cultureKeys.all }) }); }
export function useSubmitContribution() { const client = useQueryClient(); return useMutation({ mutationFn: cultureApi.submitContribution, onSuccess: () => client.invalidateQueries({ queryKey: cultureKeys.all }) }); }
export function useMyCultureContributions() { const demo = useDemoMode(); return useQuery({ queryKey: [...cultureKeys.all, 'mine'], queryFn: () => demo ? Promise.resolve(toSpringPage(demoCultureContents)) : cultureApi.myContributions() }); }
export function useMyCultureChallenges() { const demo = useDemoMode(); return useQuery({ queryKey: [...cultureKeys.all, 'my-challenges'], queryFn: () => demo ? Promise.resolve([]) : cultureApi.myChallenges() }); }
export function useJoinChallenge() { const demo = useDemoMode(); const client = useQueryClient(); return useMutation({ mutationFn: (id: string) => demo ? Promise.resolve({ challengeId: id, joinedAt: new Date().toISOString(), completedAt: null }) : cultureApi.joinChallenge(id), onSuccess: () => client.invalidateQueries({ queryKey: [...cultureKeys.all, 'my-challenges'] }) }); }
export function useSubmitChallenge() { const demo = useDemoMode(); return useMutation({ mutationFn: ({ id, postId }: { id: string; postId: string }) => demo ? Promise.resolve({ id: `demo-submission-${id}`, status: 'PENDING' }) : cultureApi.submitChallenge(id, { postId, mediaIds: [], consentConfirmed: true, recordsAnotherPerson: false, anonymized: false, involvesMinor: false, sacredCeremony: false, personalData: false, hateSpeechSuspected: false }) }); }
export function useCultureGraphRelations(id?: string) { const demo = useDemoMode(); return useQuery({ queryKey: [...cultureKeys.all, 'graph', id ?? ''], enabled: Boolean(id), queryFn: () => demo ? Promise.resolve([]) : cultureApi.relatedCulture(id!) }); }
