import { useState } from 'react';
import { Alert, ScrollView, Text, TouchableOpacity, View } from 'react-native';
import { Stack, useRouter } from 'expo-router';
import { SafeScreen } from '@/components/ui/SafeScreen'; import { Icon } from '@/components/ui/Icon'; import { CTAButton } from '@/components/ui/CTAButton'; import { Input } from '@/components/ui/Input'; import { Stepper } from '@/components/ui/Stepper'; import { FormSelect } from '@/components/ui/FormSelect'; import { DateTimeField } from '@/components/ui/DateTimeField';
import { usePartnerStore } from '@/features/partner/partner.store'; import { useThemeStore } from '@/features/theme/theme.store'; import { formValidation } from '@/utils/formValidation'; import { establishments } from '@/features/partner-dashboard/mockData';

const CATEGORIES = ['Musique', 'Culture', 'Gastronomie', 'Sport', 'Business', 'Communauté'].map((value) => ({ label: value, value }));
const TYPES = ['Concert', 'Festival', 'Atelier', 'Conférence', 'Exposition', 'Rencontre'].map((value) => ({ label: value, value }));
export default function AddEventStep1Screen() {
  const router = useRouter(); const colors = useThemeStore((state) => state.colors); const { eventForm, setEventForm, setEventStep } = usePartnerStore();
  const [name, setName] = useState(eventForm.name || ''); const [location, setLocation] = useState(eventForm.location || ''); const [category, setCategory] = useState(eventForm.category || ''); const [place, setPlace] = useState(eventForm.place || ''); const [type, setType] = useState(eventForm.type || ''); const [startDate, setStartDate] = useState(eventForm.start_date || ''); const [startTime, setStartTime] = useState(eventForm.start_time || ''); const [errors, setErrors] = useState<Record<string, string | undefined>>({});
  const continueForm = () => { const next = { name: formValidation.required(name, 'Nom'), location: formValidation.required(location, 'Lieu'), category: formValidation.required(category, 'Catégorie'), type: formValidation.required(type, 'Type'), startDate: formValidation.date(startDate, 'Date de début', true), startTime: formValidation.required(startTime, 'Heure de début') }; setErrors(next); const first = Object.values(next).find(Boolean); if (first) return Alert.alert('Événement à vérifier', first); setEventForm({ name: name.trim(), location: location.trim(), category, place, type, start_date: startDate, start_time: startTime }); setEventStep(2); router.push('/(partner)/add-event-step2'); };
  return <SafeScreen><Stack.Screen options={{ headerShown: false }} /><View className="flex-row items-center border-b px-4 py-3" style={{ borderColor: colors.border }}><TouchableOpacity onPress={() => router.back()} className="h-11 w-11 items-center justify-center rounded-full" style={{ backgroundColor: colors.elevated }}><Icon name="arrow-back" size={22} color={colors.text} /></TouchableOpacity><View className="ml-3"><Text className="text-lg font-extrabold" style={{ color: colors.text }}>Ajouter un événement</Text><Text className="text-xs" style={{ color: colors.textSecondary }}>Informations principales</Text></View></View>
    <ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 120 }} keyboardShouldPersistTaps="handled"><Stepper currentStep={1} totalSteps={4} /><View className="gap-4"><Input label="Nom de l’événement *" value={name} onChangeText={setName} error={errors.name} placeholder="Ex. Festival des cultures" autoCapitalize="sentences" /><Input label="Adresse ou lieu *" value={location} onChangeText={setLocation} error={errors.location} placeholder="Ex. Palais des Congrès, Yaoundé" /><FormSelect label="Catégorie" value={category} options={CATEGORIES} onChange={setCategory} error={errors.category} required /><FormSelect label="Établissement associé" value={place} options={establishments.map((item) => ({ label: item.name, value: item.name, description: item.address }))} onChange={setPlace} placeholder="Aucun établissement" /><FormSelect label="Type d’événement" value={type} options={TYPES} onChange={setType} error={errors.type} required /><DateTimeField label="Date de début" value={startDate} onChange={setStartDate} minimumDate={new Date()} error={errors.startDate} required /><DateTimeField label="Heure de début" value={startTime} onChange={setStartTime} mode="time" error={errors.startTime} required /></View></ScrollView>
    <View className="absolute bottom-0 left-0 right-0 border-t px-4 py-4" style={{ backgroundColor: colors.background, borderColor: colors.border }}><CTAButton title="Continuer" onPress={continueForm} /></View>
  </SafeScreen>;
}
