import { ActivityIndicator, FlatList, Text, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeScreen } from '@/components/ui/SafeScreen';
import { Icon } from '@/components/ui/Icon';
import { useThemeStore } from '@/features/theme/theme.store';
import { useCountryStore } from '@/features/country/country.store';
import { ArtisanCard } from '@/features/artisans/components/ArtisanCard';
import { useArtisans } from '@/features/artisans/artisans.hooks';
export default function ArtisansScreen() { const router = useRouter(); const colors = useThemeStore((state) => state.colors); const countryCode = useCountryStore((state) => state.selectedCountryCode ?? undefined); const artisans = useArtisans({ countryCode, size: 30 }); return <SafeScreen><View className="flex-row items-center px-4 py-3"><TouchableOpacity onPress={() => router.back()} className="-ml-2 p-2"><Icon name="chevron-back" size={24} color={colors.text} /></TouchableOpacity><View className="ml-2"><Text className="text-2xl font-extrabold" style={{ color: colors.text }}>Artisans</Text><Text className="mt-1 text-sm" style={{ color: colors.textSecondary }}>Des savoir-faire à rencontrer.</Text></View></View>{artisans.isLoading ? <View className="flex-1 items-center justify-center"><ActivityIndicator color={colors.primary} /></View> : artisans.isError ? <View className="flex-1 items-center justify-center"><Text style={{ color: colors.textSecondary }}>Les profils artisans sont indisponibles.</Text><TouchableOpacity onPress={() => artisans.refetch()} className="mt-4"><Text className="font-bold text-[#EF4444]">Réessayer</Text></TouchableOpacity></View> : <FlatList data={artisans.data?.content ?? []} keyExtractor={(item) => item.partnerId} contentContainerStyle={{ padding: 16, paddingBottom: 32 }} renderItem={({ item }) => <View className="mb-3"><ArtisanCard artisan={item} onPress={() => router.push(`/(explore)/artisans/${item.partnerId}`)} /></View>} ListEmptyComponent={<Text className="p-8 text-center" style={{ color: colors.textSecondary }}>Aucun artisan ne correspond à cette sélection.</Text>} />}</SafeScreen>; }
