import { ActivityIndicator, FlatList, Text, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeScreen } from '@/components/ui/SafeScreen';
import { Icon } from '@/components/ui/Icon';
import { useThemeStore } from '@/features/theme/theme.store';
import { ArtworkCard } from '@/features/artworks/components/ArtworkCard';
import { useArtworks } from '@/features/artworks/artworks.hooks';
import { useCountryStore } from '@/features/country/country.store';
export default function ArtworksScreen() { const router = useRouter(); const colors = useThemeStore((state) => state.colors); const countryCode = useCountryStore((state) => state.selectedCountryCode ?? undefined); const artworks = useArtworks({ countryCode, size: 30 }); return <SafeScreen><View className="flex-row items-center px-4 py-3"><TouchableOpacity onPress={() => router.back()} className="-ml-2 p-2"><Icon name="chevron-back" size={24} color={colors.text} /></TouchableOpacity><View className="ml-2"><Text className="text-2xl font-extrabold" style={{ color: colors.text }}>Œuvres</Text><Text className="mt-1 text-sm" style={{ color: colors.textSecondary }}>Créations, histoires et savoir-faire.</Text></View></View>{artworks.isLoading ? <View className="flex-1 items-center justify-center"><ActivityIndicator color={colors.primary} /></View> : artworks.isError ? <View className="flex-1 items-center justify-center px-8"><Text style={{ color: colors.textSecondary }}>Les œuvres ne peuvent pas être chargées.</Text><TouchableOpacity onPress={() => artworks.refetch()} className="mt-4"><Text className="font-bold text-[#EF4444]">Réessayer</Text></TouchableOpacity></View> : <FlatList data={artworks.data?.content ?? []} keyExtractor={(item) => item.assetId} contentContainerStyle={{ padding: 16, paddingBottom: 32 }} renderItem={({ item }) => <View className="mb-3"><ArtworkCard artwork={item} onPress={() => router.push(`/(explore)/artworks/${item.assetId}`)} /></View>} ListEmptyComponent={<Text className="p-8 text-center" style={{ color: colors.textSecondary }}>Aucune œuvre disponible dans cette sélection.</Text>} />}</SafeScreen>; }
