import { ScrollView, Text, TouchableOpacity, View } from 'react-native';
import { Image } from 'expo-image';
import { useRouter } from 'expo-router';
import { SafeScreen } from '@/components/ui/SafeScreen'; import { Icon } from '@/components/ui/Icon'; import { useThemeStore } from '@/features/theme/theme.store';
const MODULES=[
  {title:'Proverbes',count:'100 paroles',description:'Sagesse, contexte et usage par région.',icon:'chatbubbles-outline',image:'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=900',route:'/(explore)/proverbs'},
  {title:'Recettes',count:'100 recettes',description:'Menus camerounais classés et détaillés.',icon:'restaurant-outline',image:'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=900',route:'/(explore)/recipes'},
  {title:'Langues',count:'10 langues',description:'Leçons, prononciation et quiz personnalisables.',icon:'language-outline',image:'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=900',route:'/(explore)/languages'},
  {title:'Contes et mémoires',count:'Récits vérifiés',description:'Histoires orales et mémoire communautaire.',icon:'book-outline',image:'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=900',route:'/(explore)/stories'},
  {title:'Arts et savoir-faire',count:'8 catégories',description:'Œuvres, artistes, techniques et récits audio.',icon:'color-palette-outline',image:'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=900',route:'/(explore)/art-categories'},
  {title:'Défis de transmission',count:'Activités pratiques',description:'Documenter, apprendre et contribuer.',icon:'trophy-outline',image:'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=900',route:'/(explore)/challenges'},
];
export default function TransmissionScreen(){const router=useRouter();const colors=useThemeStore((s)=>s.colors);return <SafeScreen><ScrollView contentContainerStyle={{paddingBottom:40}}><View className="flex-row items-center px-4 py-3"><TouchableOpacity onPress={()=>router.back()} className="h-11 w-11 items-center justify-center"><Icon name="chevron-back" size={24} color={colors.text}/></TouchableOpacity><View className="ml-2 flex-1"><Text className="text-2xl font-extrabold" style={{color:colors.text}}>À transmettre</Text><Text className="mt-1 text-sm" style={{color:colors.textSecondary}}>Un accès clair aux savoirs, sans sections répétées.</Text></View></View><View className="px-4 pt-3">{MODULES.map((item)=><TouchableOpacity key={item.title} onPress={()=>router.push(item.route as never)} className="mb-4 overflow-hidden rounded-3xl border" style={{backgroundColor:colors.card,borderColor:colors.border}}><Image source={{uri:item.image}} style={{width:'100%',height:130}} contentFit="cover"/><View className="p-4"><View className="flex-row items-center"><View className="h-11 w-11 items-center justify-center rounded-xl" style={{backgroundColor:colors.accentSoft}}><Icon name={item.icon} size={22} color={colors.primary}/></View><View className="ml-3 flex-1"><Text className="text-lg font-extrabold" style={{color:colors.text}}>{item.title}</Text><Text className="text-xs font-bold text-[#EF4444]">{item.count}</Text></View><Icon name="chevron-forward" size={20} color={colors.textMuted}/></View><Text className="mt-3 text-sm leading-5" style={{color:colors.textSecondary}}>{item.description}</Text></View></TouchableOpacity>)}</View></ScrollView></SafeScreen>}
