import type { Event } from './types';

export const mockEvents: Event[] = [
  {
    id: 1,
    title: 'Festival Ngondo 2025',
    description: 'Le Festival Ngondo est une célébration annuelle des traditions du peuple Sawa. Venez découvrir les danses traditionnelles, les courses de pirogues et la culture authentique.',
    cover_image_url: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
    start_date: '2025-05-20',
    end_date: '2025-05-22',
    start_time: '09:00',
    end_time: '20:00',
    duration_hours: 3,
    location: 'Douala',
    address: 'Berge du Wouri',
    city: 'Douala',
    organizer: {
      id: 1,
      username: 'ngondo_official',
      display_name: 'Ngondo Official',
      avatar_url: null,
      is_verified: true,
    },
    participants_count: 2400,
    participants: [],
    is_participating: false,
    is_saved: false,
    price: null,
    currency: 'FCFA',
    created_at: '2024-01-10T00:00:00Z',
    program: [
      { date: '20 Mai', title: 'Ouverture officielle', description: 'Cérémonie d\'ouverture avec les autorités traditionnelles' },
      { date: '21 Mai', title: 'Défilé des pirogues', description: 'Course traditionnelle de pirogues sur le fleuve' },
      { date: '22 Mai', title: 'Concerts & animations', description: 'Spectacles musicaux et danses traditionnelles' },
    ],
  },
  {
    id: 2,
    title: 'Concert Nguelakan',
    description: 'Concert exceptionnel de musique traditionnelle camerounaise au cœur de Maroua.',
    cover_image_url: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800',
    start_date: '2025-06-14',
    end_date: '2025-06-14',
    start_time: '19:00',
    end_time: '23:00',
    duration_hours: 4,
    location: 'Maroua',
    address: 'Centre Culturel',
    city: 'Maroua',
    organizer: {
      id: 2,
      username: 'culturecam',
      display_name: 'Culture Cameroun',
      avatar_url: null,
      is_verified: true,
    },
    participants_count: 850,
    participants: [],
    is_participating: false,
    is_saved: true,
    price: 5000,
    currency: 'FCFA',
    created_at: '2024-02-05T00:00:00Z',
  },
  {
    id: 3,
    title: 'Festival Ngonda 2025',
    description: 'Célébration culturelle annuelle à Yaoundé avec des performances artistiques exceptionnelles.',
    cover_image_url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800',
    start_date: '2025-07-10',
    end_date: '2025-07-12',
    start_time: '10:00',
    end_time: '22:00',
    location: 'Yaoundé',
    address: 'Palais des Sports',
    city: 'Yaoundé',
    organizer: {
      id: 3,
      username: 'yaounde_events',
      display_name: 'Yaoundé Events',
      avatar_url: null,
      is_verified: false,
    },
    participants_count: 1200,
    participants: [],
    is_participating: false,
    is_saved: false,
    price: 3000,
    currency: 'FCFA',
    created_at: '2024-01-25T00:00:00Z',
  },
  {
    id: 4,
    title: 'Salon du Tourisme',
    description: 'Découvrez les destinations touristiques du Cameroun lors de ce salon professionnel.',
    cover_image_url: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800',
    start_date: '2025-08-05',
    end_date: '2025-08-07',
    start_time: '09:00',
    end_time: '18:00',
    location: 'Douala',
    address: 'Centre de Congrès',
    city: 'Douala',
    organizer: {
      id: 4,
      username: 'mintour_cm',
      display_name: 'MINTOUR',
      avatar_url: null,
      is_verified: true,
    },
    participants_count: 3500,
    participants: [],
    is_participating: true,
    is_saved: true,
    price: null,
    currency: 'FCFA',
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: 5,
    title: 'Course de Pirogues',
    description: 'Compétition traditionnelle de courses de pirogues sur le fleuve Sanaga.',
    cover_image_url: 'https://images.unsplash.com/photo-1502933691298-84fc14542831?w=800',
    start_date: '2025-09-15',
    end_date: '2025-09-15',
    start_time: '14:00',
    end_time: '18:00',
    duration_hours: 4,
    location: 'Edéa',
    address: 'Berges de la Sanaga',
    city: 'Edéa',
    organizer: {
      id: 5,
      username: 'pirogue_racing',
      display_name: 'Pirogue Racing',
      avatar_url: null,
      is_verified: false,
    },
    participants_count: 450,
    participants: [],
    is_participating: false,
    is_saved: false,
    price: 2000,
    currency: 'FCFA',
    created_at: '2024-02-20T00:00:00Z',
  },
  {
    id: 6,
    title: 'Fête de la Musique',
    description: 'Célébration annuelle de la musique avec des concerts gratuits partout en ville.',
    cover_image_url: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
    start_date: '2025-06-21',
    end_date: '2025-06-21',
    start_time: '18:00',
    end_time: '23:59',
    location: 'Yaoundé',
    address: 'Divers lieux',
    city: 'Yaoundé',
    organizer: {
      id: 6,
      username: 'fete_musique',
      display_name: 'Fête de la Musique',
      avatar_url: null,
      is_verified: true,
    },
    participants_count: 8000,
    participants: [],
    is_participating: false,
    is_saved: false,
    price: null,
    currency: 'FCFA',
    created_at: '2024-04-01T00:00:00Z',
  },
];
