import type { Event } from './types';

export const mockEvents: Event[] = [
  {
    id: 1,
    title: 'Concert Live à Douala',
    description: 'Soirée musicale exceptionnelle avec les meilleurs artistes du moment. Une ambiance électrique garantie avec des performances live inoubliables. Billet standard et VIP disponibles.',
    cover_image_url: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
    start_date: '2025-05-24',
    end_date: '2025-05-24',
    start_time: '20:00',
    end_time: '02:00',
    duration_hours: 6,
    location: 'La Falaise Resort, Douala',
    address: 'Route de Yégémbé, Douala',
    city: 'Douala',
    organizer: {
      id: 1,
      username: 'falaise_events',
      display_name: 'La Falaise Events',
      avatar_url: 'https://i.pravatar.cc/150?img=15',
      is_verified: true,
      user_type: 'partner',
    },
    participants_count: 136,
    max_participants: 500,
    interested_count: 45,
    participants: [
      {
        id: 2,
        username: 'jean_paul',
        display_name: 'Jean Paul',
        avatar_url: 'https://i.pravatar.cc/150?img=12',
        is_verified: false,
        user_type: 'user',
      },
      {
        id: 3,
        username: 'marie_d',
        display_name: 'Marie D.',
        avatar_url: 'https://i.pravatar.cc/150?img=5',
        is_verified: false,
        user_type: 'user',
      },
      {
        id: 4,
        username: 'paul_k',
        display_name: 'Paul K.',
        avatar_url: 'https://i.pravatar.cc/150?img=8',
        is_verified: true,
        user_type: 'user',
      },
      {
        id: 5,
        username: 'sarah_m',
        display_name: 'Sarah M.',
        avatar_url: 'https://i.pravatar.cc/150?img=20',
        is_verified: false,
        user_type: 'user',
      },
    ],
    is_participating: false,
    is_saved: false,
    price: 5000,
    vip_price: 10000,
    currency: 'FCFA',
    created_at: '2024-01-10T00:00:00Z',
    ticket_types: [
      {
        id: '1',
        type: 'standard',
        label: 'Billet standard',
        price: 5000,
        available: true,
      },
      {
        id: '2',
        type: 'vip',
        label: 'VIP',
        price: 10000,
        available: true,
      }
    ],
  },
  {
    id: 2,
    title: 'Festival Ngondo 2025',
    description: 'Le Festival Ngondo est une célébration annuelle des traditions du peuple Sawa.',
    cover_image_url: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
    start_date: '2025-12-09',
    end_date: '2025-12-15',
    start_time: '09:00',
    end_time: '20:00',
    location: 'Berge du Wouri',
    address: 'Berge du Wouri, Douala',
    city: 'Douala',
    organizer: {
      id: 6,
      username: 'ngondo_official',
      display_name: 'Ngondo Official',
      avatar_url: null,
      is_verified: true,
      user_type: 'partner',
    },
    participants_count: 2400,
    participants: [],
    is_participating: false,
    is_saved: false,
    price: null,
    currency: 'FCFA',
    created_at: '2024-01-10T00:00:00Z',
  },
];
