import { ActivityIndicator, ScrollView, Text, TouchableOpacity, View } from 'react-native';
import { useRouter, type Href } from 'expo-router';
import { SafeScreen } from '@/components/ui/SafeScreen';
import { Icon } from '@/components/ui/Icon';
import { useUserBadges } from '@/features/social-graph/useBadges';
import { useThemeStore } from '@/features/theme/theme.store';

export default function BadgesScreen() {
  const router = useRouter(); const colors = useThemeStore((state) => state.colors);
  const { data: badges = [], isLoading, isError, refetch } = useUserBadges();
  return <SafeScreen><View className="flex-row items-center border-b px-4 pb-3 pt-2" style={{ borderColor: colors.border }}><TouchableOpacity onPress={() => router.canGoBack() ? router.back() : router.replace('/(social-graph)/passport')} className="h-10 w-10 items-center justify-center rounded-full" style={{ backgroundColor: colors.elevated }}><Icon name="chevron-back" size={22} color={colors.text} /></TouchableOpacity><View className="ml-3 flex-1"><Text className="text-xl font-extrabold" style={{ color: colors.text }}>Mes badges</Text><Text className="text-xs" style={{ color: colors.textSecondary }}>{badges.length} badge{badges.length > 1 ? 's' : ''} obtenu{badges.length > 1 ? 's' : ''}</Text></View><Icon name="trophy" size={23} color="#EF4444" /></View>{isLoading ? <ActivityIndicator className="mt-20" color={colors.primary} /> : isError ? <View className="flex-1 items-center justify-center px-8"><Text style={{ color: colors.textSecondary }}>Impossible de charger les badges.</Text><TouchableOpacity onPress={() => void refetch()} className="mt-4 rounded-xl bg-[#EF4444] px-4 py-3"><Text className="font-bold text-white">Réessayer</Text></TouchableOpacity></View> : <ScrollView contentContainerStyle={{ padding: 16, paddingBottom: 36 }}>{badges.length ? badges.map((badge) => <TouchableOpacity key={String(badge.id)} onPress={() => router.push(`/(social-graph)/badges/${badge.id}` as Href)} className="mb-3 flex-row items-center rounded-2xl border p-4" style={{ backgroundColor: colors.card, borderColor: colors.border }}><View className="h-11 w-11 items-center justify-center rounded-xl bg-[#FEF2F2]"><Icon name="trophy" size={21} color="#EF4444" /></View><View className="ml-3 flex-1"><Text className="font-bold" style={{ color: colors.text }}>{badge.name}</Text><Text className="mt-1 text-xs" style={{ color: colors.textSecondary }}>{badge.description}</Text></View></TouchableOpacity>) : <View className="items-center py-20"><Icon name="trophy-outline" size={38} color={colors.textMuted} /><Text className="mt-3 text-center" style={{ color: colors.textSecondary }}>Aucun badge obtenu pour le moment.</Text></View>}</ScrollView>}</SafeScreen>;
}
