// Données fictives pour le système de badges
import type { Badge, BadgeLevel, XPAction, UserBadgeStats } from './types';

export const BADGE_LEVELS: Record<string, BadgeLevel[]> = {
  explorateur: [
    {
      level: 1,
      name: 'Découvreur',
      xp_required: 0,
      reward: '+50 XP par lieu découvert',
      icon_color: '#10B981',
      is_unlocked: true,
    },
    {
      level: 2,
      name: 'Aventurier',
      xp_required: 500,
      reward: '+100 XP par lieu découvert',
      icon_color: '#3B82F6',
      is_unlocked: true,
    },
    {
      level: 3,
      name: 'Voyageur',
      xp_required: 1000,
      reward: '+150 XP par lieu découvert',
      icon_color: '#8B5CF6',
      is_unlocked: true,
    },
    {
      level: 4,
      name: 'Globe-trotter',
      xp_required: 2000,
      reward: '+200 XP par lieu découvert',
      icon_color: '#F59E0B',
      is_unlocked: false,
    },
    {
      level: 5,
      name: 'Expert',
      xp_required: 3000,
      reward: 'Badge exclusif + visibilité accrue',
      icon_color: '#EF4444',
      is_unlocked: false,
    },
  ],
  createur: [
    {
      level: 1,
      name: 'Débutant',
      xp_required: 0,
      icon_color: '#10B981',
      is_unlocked: true,
    },
    {
      level: 2,
      name: 'Amateur',
      xp_required: 500,
      icon_color: '#3B82F6',
      is_unlocked: true,
    },
    {
      level: 3,
      name: 'Créatif',
      xp_required: 1250,
      icon_color: '#8B5CF6',
      is_unlocked: false,
    },
    {
      level: 4,
      name: 'Influenceur',
      xp_required: 2500,
      icon_color: '#F59E0B',
      is_unlocked: false,
    },
  ],
  contributeur: [
    {
      level: 1,
      name: 'Novice',
      xp_required: 0,
      icon_color: '#10B981',
      is_unlocked: true,
    },
    {
      level: 2,
      name: 'Actif',
      xp_required: 684,
      icon_color: '#3B82F6',
      is_unlocked: false,
    },
    {
      level: 3,
      name: 'Engagé',
      xp_required: 1500,
      icon_color: '#8B5CF6',
      is_unlocked: false,
    },
  ],
  topGuide: [
    {
      level: 1,
      name: 'Guide Junior',
      xp_required: 0,
      icon_color: '#10B981',
      is_unlocked: false,
    },
    {
      level: 2,
      name: 'Guide',
      xp_required: 550,
      icon_color: '#3B82F6',
      is_unlocked: false,
    },
    {
      level: 3,
      name: 'Top Guide',
      xp_required: 1000,
      icon_color: '#EF4444',
      is_unlocked: false,
    },
  ],
};

export const MOCK_BADGES: Badge[] = [
  {
    id: 1,
    name: 'Explorateur',
    slug: 'explorateur',
    description: 'Visitez de nouveaux lieux, découvrez des endroits uniques et partagez vos découvertes',
    icon_url: 'https://via.placeholder.com/120x120/10B981/ffffff?text=MAP',
    category: 'exploration',
    current_level: 3,
    max_level: 5,
    current_xp: 2480,
    next_level_xp: 3000,
    total_xp: 2480,
    is_unlocked: true,
    unlocked_at: '2024-01-15T10:00:00Z',
    levels: BADGE_LEVELS.explorateur,
  },
  {
    id: 2,
    name: 'Créateur',
    slug: 'createur',
    description: "Publiez du contenu, partagez vos photos, vidéos et organisez des événements pour inspirer la communauté",
    icon_url: 'https://via.placeholder.com/120x120/8B5CF6/ffffff?text=XP',
    category: 'creation',
    current_level: 2,
    max_level: 4,
    current_xp: 1250,
    next_level_xp: 2000,
    total_xp: 1250,
    is_unlocked: true,
    unlocked_at: '2024-02-01T14:30:00Z',
    levels: BADGE_LEVELS.createur,
  },
  {
    id: 3,
    name: 'Contributeur',
    slug: 'contributeur',
    description: 'Aidez la communauté en notant des lieux, partageant vos avis et en évaluant du contenu',
    icon_url: 'https://via.placeholder.com/120x120/F59E0B/ffffff?text=⭐',
    category: 'contribution',
    current_level: 1,
    max_level: 3,
    current_xp: 684,
    next_level_xp: 1500,
    total_xp: 684,
    is_unlocked: true,
    unlocked_at: '2024-03-10T09:15:00Z',
    levels: BADGE_LEVELS.contributeur,
  },
  {
    id: 4,
    name: 'Top Guide',
    slug: 'topGuide',
    description: 'Aidez la communauté et recevez des avis positifs',
    icon_url: 'https://via.placeholder.com/120x120/EF4444/ffffff?text=HOT',
    category: 'social',
    current_level: 0,
    max_level: 3,
    current_xp: 550,
    next_level_xp: 1000,
    total_xp: 550,
    is_unlocked: false,
    levels: BADGE_LEVELS.topGuide,
  },
];

export const XP_ACTIONS: XPAction[] = [
  {
    id: 1,
    action: 'Check-in dans un lieu',
    xp_reward: 50,
    icon: 'location',
    description: 'Visitez un nouveau lieu et faites un check-in',
  },
  {
    id: 2,
    action: 'Enregistrer un lieu',
    xp_reward: 30,
    icon: 'bookmark',
    description: 'Sauvegardez vos lieux préférés',
  },
  {
    id: 3,
    action: 'Publier une expérience',
    xp_reward: 100,
    icon: 'camera',
    description: 'Partagez vos moments et expériences',
  },
  {
    id: 4,
    action: 'Inviter un ami',
    xp_reward: 100,
    icon: 'person-add',
    description: 'Invitez vos amis à rejoindre Yeyamo',
  },
];

export const MOCK_USER_STATS: UserBadgeStats = {
  total_badges: 4,
  unlocked_badges: 3,
  total_xp: 4964,
  level: 12,
  rank: 'Explorateur Confirmé',
};
