import type { PassportData } from './passport.types';

export const MOCK_PASSPORT: PassportData = {
  currentLevel: 12,
  currentTitle: 'Explorateur confirmé',
  totalXP: 4964,
  currentLevelXP: 964,
  nextLevelXP: 1500,
  nationalRank: 284,
  regionalRank: 37,
  activeDays: 86,
  currentStreak: 8,
  bestStreak: 21,
  xpHistory: [
    { id: 'xp1', label: 'Mission : Escapade du week-end', date: 'Aujourd’hui, 14:20', xp: 250, icon: 'flag' },
    { id: 'xp2', label: 'Check-in à la Lobé', date: 'Hier, 17:45', xp: 50, icon: 'location' },
    { id: 'xp3', label: 'Nouvelle publication', date: '12 juillet', xp: 100, icon: 'camera' },
    { id: 'xp4', label: 'Avis utile publié', date: '10 juillet', xp: 75, icon: 'star' },
  ],
  titles: [
    { id: 't1', name: 'Voyageur débutant', description: 'Vos premiers pas dans la communauté.', xpRequired: 0, progress: 100, unlocked: true, icon: 'footsteps' },
    { id: 't2', name: 'Explorateur', description: 'Découvrez 10 lieux différents.', xpRequired: 750, progress: 100, unlocked: true, icon: 'compass' },
    { id: 't3', name: 'Aventurier', description: 'Explorez trois régions du Cameroun.', xpRequired: 2000, progress: 100, unlocked: true, icon: 'trail-sign' },
    { id: 't4', name: 'Grand Voyageur', description: 'Atteignez 7 500 XP de voyage.', xpRequired: 7500, progress: 66, unlocked: false, icon: 'airplane' },
    { id: 't5', name: 'Guide Local', description: 'Publiez 25 avis utiles.', xpRequired: 10000, progress: 48, unlocked: false, icon: 'map' },
    { id: 't6', name: 'Ambassadeur', description: 'Faites découvrir votre région.', xpRequired: 18000, progress: 28, unlocked: false, icon: 'ribbon' },
    { id: 't7', name: 'Légende YeYamo', description: 'Accomplissez tous les grands défis.', xpRequired: 30000, progress: 16, unlocked: false, icon: 'diamond' },
  ],
  exploration: {
    code: 'CM', name: 'Cameroun', regionsVisited: 4, regionsTotal: 10, citiesVisited: 12, placesDiscovered: 47,
    regions: [
      { id: 'littoral', name: 'Littoral', visited: true, cities: 3, places: 19, color: '#EF4444' },
      { id: 'sud', name: 'Sud', visited: true, cities: 2, places: 11, color: '#F97316' },
      { id: 'centre', name: 'Centre', visited: true, cities: 4, places: 10, color: '#F59E0B' },
      { id: 'ouest', name: 'Ouest', visited: true, cities: 3, places: 7, color: '#8B5CF6' },
      { id: 'nord-ouest', name: 'Nord-Ouest', visited: false, cities: 0, places: 0, color: '#CBD5E1' },
      { id: 'sud-ouest', name: 'Sud-Ouest', visited: false, cities: 0, places: 0, color: '#CBD5E1' },
      { id: 'est', name: 'Est', visited: false, cities: 0, places: 0, color: '#CBD5E1' },
      { id: 'adamaoua', name: 'Adamaoua', visited: false, cities: 0, places: 0, color: '#CBD5E1' },
      { id: 'nord', name: 'Nord', visited: false, cities: 0, places: 0, color: '#CBD5E1' },
      { id: 'extreme-nord', name: 'Extrême-Nord', visited: false, cities: 0, places: 0, color: '#CBD5E1' },
    ],
  },
  statistics: [
    { id: 'posts', label: 'Publications', value: 128, icon: 'images', color: '#EF4444' },
    { id: 'likes', label: 'Likes reçus', value: 2840, icon: 'heart', color: '#EC4899' },
    { id: 'comments', label: 'Commentaires', value: 416, icon: 'chatbubble', color: '#8B5CF6' },
    { id: 'shares', label: 'Partages', value: 193, icon: 'paper-plane', color: '#2563EB' },
    { id: 'checkins', label: 'Check-ins', value: 47, icon: 'location', color: '#16A34A' },
    { id: 'bookings', label: 'Réservations', value: 18, icon: 'ticket', color: '#F59E0B' },
    { id: 'events', label: 'Événements', value: 9, icon: 'calendar', color: '#F97316' },
    { id: 'days', label: 'Jours actifs', value: 86, icon: 'flame', color: '#DC2626' },
  ],
  timeline: [
    { id: 'e1', type: 'badge', title: 'Badge Gastronomie débloqué', subtitle: 'Votre 10e restaurant découvert', date: 'Aujourd’hui', icon: 'restaurant', color: '#F59E0B' },
    { id: 'e2', type: 'mission', title: 'Mission accomplie', subtitle: 'Escapade du week-end · +250 XP', date: 'Aujourd’hui', icon: 'flag', color: '#EF4444' },
    { id: 'e3', type: 'city', title: 'Nouvelle ville : Kribi', subtitle: 'Votre 12e ville camerounaise', date: '15 juillet', icon: 'business', color: '#2563EB' },
    { id: 'e4', type: 'level', title: 'Niveau 12 atteint', subtitle: 'Vous êtes Explorateur confirmé', date: '9 juillet', icon: 'sparkles', color: '#8B5CF6' },
    { id: 'e5', type: 'region', title: 'Région du Sud explorée', subtitle: '11 lieux découverts', date: '2 juillet', icon: 'map', color: '#16A34A' },
    { id: 'e6', type: 'reservation', title: 'Première réservation', subtitle: 'Séjour à La Falaise Resort', date: '18 juin', icon: 'ticket', color: '#F97316' },
  ],
  missions: [
    { id: 'm1', type: 'daily', title: 'Curieux du jour', description: 'Découvrez un nouveau lieu', progress: 1, target: 1, xpReward: 50, timeLeft: '8 h 24 min', icon: 'compass' },
    { id: 'm2', type: 'daily', title: 'Voix de la communauté', description: 'Publiez un commentaire utile', progress: 1, target: 2, xpReward: 40, timeLeft: '8 h 24 min', icon: 'chatbubble' },
    { id: 'm3', type: 'weekly', title: 'Explorateur urbain', description: 'Visitez cinq lieux cette semaine', progress: 3, target: 5, xpReward: 300, timeLeft: '3 jours', icon: 'map' },
    { id: 'm4', type: 'weekly', title: 'Carnet de voyage', description: 'Publiez trois expériences', progress: 2, target: 3, xpReward: 250, timeLeft: '3 jours', icon: 'images' },
    { id: 'm5', type: 'special', title: 'Le Cameroun en fête', description: 'Participez à deux événements culturels', progress: 1, target: 2, xpReward: 750, timeLeft: '12 jours', icon: 'trophy' },
  ],
  collections: [
    { id: 'c1', name: 'Régions visitées', current: 4, target: 10, icon: 'map', color: '#EF4444' },
    { id: 'c2', name: 'Monuments', current: 8, target: 25, icon: 'business', color: '#F59E0B' },
    { id: 'c3', name: 'Musées', current: 5, target: 18, icon: 'library', color: '#8B5CF6' },
    { id: 'c4', name: 'Restaurants', current: 19, target: 50, icon: 'restaurant', color: '#F97316' },
    { id: 'c5', name: 'Plages', current: 6, target: 16, icon: 'water', color: '#2563EB' },
    { id: 'c6', name: 'Chutes', current: 3, target: 12, icon: 'rainy', color: '#06B6D4' },
    { id: 'c7', name: 'Montagnes', current: 2, target: 10, icon: 'triangle', color: '#16A34A' },
    { id: 'c8', name: 'Parcs', current: 4, target: 20, icon: 'leaf', color: '#22C55E' },
  ],
  leaderboard: [
    { id: 'u1', rank: 1, name: 'Marie Voyage', city: 'Yaoundé', xp: 18420, avatarUrl: 'https://i.pravatar.cc/120?img=5' },
    { id: 'u2', rank: 2, name: 'Arthur Local', city: 'Douala', xp: 16980, avatarUrl: 'https://i.pravatar.cc/120?img=12' },
    { id: 'u3', rank: 3, name: 'Sarah Explore', city: 'Bafoussam', xp: 15840, avatarUrl: 'https://i.pravatar.cc/120?img=32' },
    { id: 'me', rank: 284, name: 'Daryl Demo', city: 'Douala', xp: 4964, avatarUrl: 'https://i.pravatar.cc/120?img=11', isCurrentUser: true },
  ],
  rewards: [
    { id: 'r1', name: 'Badge Explorateur', type: 'badge', description: 'Votre premier badge premium.', unlocked: true, icon: 'compass', color: '#16A34A' },
    { id: 'r2', name: 'Titre Aventurier', type: 'title', description: 'Visible sur votre profil public.', unlocked: true, icon: 'ribbon', color: '#8B5CF6' },
    { id: 'r3', name: 'Cadre Flamme', type: 'frame', description: 'Série de 7 jours atteinte.', unlocked: true, icon: 'flame', color: '#EF4444' },
    { id: 'r4', name: 'Thème Forêt', type: 'theme', description: 'Débloqué au niveau 15.', unlocked: false, icon: 'color-palette', color: '#16A34A' },
    { id: 'r5', name: 'Bonus 1 000 XP', type: 'xp', description: 'Complétez dix missions spéciales.', unlocked: false, icon: 'sparkles', color: '#F59E0B' },
    { id: 'r6', name: 'Avantage partenaire', type: 'partner', description: 'Bientôt : offres exclusives de nos partenaires.', unlocked: false, icon: 'gift', color: '#2563EB' },
  ],
};
