import type { FeedPost } from './types';

export const mockFeedPosts: FeedPost[] = [
  {
    id: 1,
    type: 'image',
    caption: 'Vivre est parfait à Kribi #3 La mer, le soleil et le plaisir La Cameroun est belle de merveille #CamerounMaFierté',
    media: [
      {
        id: 1,
        type: 'image',
        url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
        thumbnail_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400',
        width: 1080,
        height: 1350,
        duration_seconds: null,
      },
    ],
    author: {
      id: 3,
      username: 'marie_kasan',
      display_name: 'Marie Kasan',
      avatar_url: 'https://i.pravatar.cc/150?img=5',
      is_verified: true,
      user_type: 'user',
    },
    likes_count: 24,
    comments_count: 4,
    shares_count: 2,
    is_liked: false,
    is_saved: false,
    place_tag: {
      id: 1,
      name: 'Kribi Beach',
      location: 'Kribi, Cameroun',
    },
    comments: [
      {
        id: '1',
        author: {
          id: 10,
          username: 'paul_r',
          display_name: 'Paul R.',
          avatar_url: 'https://i.pravatar.cc/150?img=12',
          is_verified: false,
          user_type: 'user',
        },
        text: 'Superbe photo! J\'y était le mois dernier',
        likes_count: 5,
        is_liked: false,
        created_at: 'Il y a 2h',
      },
      {
        id: '2',
        author: {
          id: 11,
          username: 'lisa_m',
          display_name: 'Lisa M.',
          avatar_url: 'https://i.pravatar.cc/150?img=20',
          is_verified: false,
          user_type: 'user',
        },
        text: 'Magnifique endroit',
        likes_count: 2,
        is_liked: true,
        created_at: 'Il y a 1h',
      },
      {
        id: '3',
        author: {
          id: 12,
          username: 'alex_k',
          display_name: 'Alex K.',
          avatar_url: 'https://i.pravatar.cc/150?img=8',
          is_verified: true,
          user_type: 'user',
        },
        text: 'J\'ai hâte d\'y aller !',
        likes_count: 1,
        is_liked: false,
        created_at: 'Il y a 30 min',
      },
      {
        id: '4',
        author: {
          id: 13,
          username: 'sarah_b',
          display_name: 'Sarah B.',
          avatar_url: 'https://i.pravatar.cc/150?img=16',
          is_verified: false,
          user_type: 'user',
        },
        text: 'Trop beau. J\'adore cette plage!',
        likes_count: 3,
        is_liked: false,
        created_at: 'Il y a 15 min',
      },
    ],
    created_at: 'Il y a 3h',
  },
];
