import { Alert, ScrollView, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Controller, useFieldArray, useForm } from 'react-hook-form';
import type { Control, FieldPath } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useRouter } from 'expo-router';
import { SafeScreen } from '@/components/ui/SafeScreen';
import { Icon } from '@/components/ui/Icon';
import { useThemeStore } from '@/features/theme/theme.store';
import { useCountryFeature } from '@/features/country/country.hooks';
import { useCountryStore } from '@/features/country/country.store';
import { useCreateCultureContribution, useCultureLanguages, useSubmitContribution } from '@/features/culture/culture.hooks';
import type { CultureContentType, CultureContributionInput } from '@/features/culture/culture.types';

type ContributionType = Extract<CultureContentType, 'STORY' | 'TRADITION' | 'PROVERB' | 'EXPRESSION' | 'RECIPE' | 'SONG'>;
const TYPES: { value: ContributionType; label: string }[] = [{ value: 'STORY', label: 'Récit' }, { value: 'TRADITION', label: 'Tradition' }, { value: 'PROVERB', label: 'Proverbe' }, { value: 'EXPRESSION', label: 'Expression' }, { value: 'RECIPE', label: 'Recette' }, { value: 'SONG', label: 'Chant' }];
const contributionSchema = z.object({
  type: z.enum(['STORY', 'TRADITION', 'PROVERB', 'EXPRESSION', 'RECIPE', 'SONG']),
  title: z.string().trim().min(1, 'Le titre est requis.'), primaryLanguageCode: z.string().min(1, 'Choisissez une langue.'),
  communityName: z.string(), summary: z.string(), body: z.string().trim().min(1, 'Le contenu est requis.'),
  ingredients: z.array(z.object({ name: z.string().trim().min(1, 'Indiquez un ingrédient.'), quantity: z.string(), unit: z.string() })),
  steps: z.array(z.object({ instruction: z.string().trim().min(1, 'Indiquez une étape.') })),
  literalTranslation: z.string(), meaning: z.string(), originLanguageCode: z.string(), audioUrl: z.string().url('L’URL audio doit être valide.').or(z.literal('')),
}).superRefine((value, context) => {
  if (value.type === 'RECIPE' && value.ingredients.length === 0) context.addIssue({ code: 'custom', path: ['ingredients'], message: 'Ajoutez au moins un ingrédient.' });
  if (value.type === 'RECIPE' && value.steps.length === 0) context.addIssue({ code: 'custom', path: ['steps'], message: 'Ajoutez au moins une étape.' });
  if (value.type === 'PROVERB' && !value.meaning.trim()) context.addIssue({ code: 'custom', path: ['meaning'], message: 'Le sens du proverbe est requis.' });
});
type ContributionValues = z.infer<typeof contributionSchema>;

export default function CultureContributionScreen() {
  const router = useRouter(); const colors = useThemeStore((state) => state.colors); const countryCode = useCountryStore((state) => state.selectedCountryCode); const languageCode = useCountryStore((state) => state.preferredLanguageCode);
  const cultureEnabled = useCountryFeature('cultureModuleEnabled'); const contentPublishingEnabled = useCountryFeature('contentPublishingEnabled'); const languages = useCultureLanguages(); const create = useCreateCultureContribution(); const submit = useSubmitContribution();
  const { control, handleSubmit, setValue, watch, formState: { errors } } = useForm<ContributionValues>({ resolver: zodResolver(contributionSchema), defaultValues: { type: 'STORY', title: '', primaryLanguageCode: languageCode ?? '', communityName: '', summary: '', body: '', ingredients: [], steps: [], literalTranslation: '', meaning: '', originLanguageCode: '', audioUrl: '' } });
  const ingredients = useFieldArray({ control, name: 'ingredients' }); const steps = useFieldArray({ control, name: 'steps' }); const type = watch('type'); const contentLanguage = watch('primaryLanguageCode');
  const publish = handleSubmit(async (values) => {
    if (!cultureEnabled || !contentPublishingEnabled) { Alert.alert('Contribution indisponible', 'La publication culturelle n’est pas activée pour ce pays.'); return; }
    if (!countryCode) { Alert.alert('Informations manquantes', 'Choisissez un pays dans vos préférences avant de publier.'); return; }
    const input: CultureContributionInput = { type: values.type, slug: values.title.toLocaleLowerCase().replace(/[^a-z0-9]+/gi, '-').replace(/(^-|-$)/g, ''), primaryLanguageCode: values.primaryLanguageCode, countryCode, communityName: values.communityName.trim() || undefined, sourceType: 'PERSONAL_CONTRIBUTION', sensitivityLevel: 'PUBLIC', title: values.title.trim(), summary: values.summary.trim() || undefined, body: values.body.trim() };
    if (values.type === 'RECIPE') input.recipeDetails = { ingredients: values.ingredients.map((item) => ({ name: item.name.trim(), quantity: item.quantity.trim() || null, unit: item.unit.trim() || null })), steps: values.steps.map((item) => ({ instruction: item.instruction.trim() })), prepTimeMinutes: null, servings: null };
    if (values.type === 'PROVERB') input.proverbDetails = { literalTranslation: values.literalTranslation.trim() || null, meaning: values.meaning.trim(), originLanguageCode: values.originLanguageCode.trim() || null, audioUrl: values.audioUrl || null };
    try { const content = await create.mutateAsync(input); await submit.mutateAsync(content.id); Alert.alert('Contribution envoyée', 'Elle sera publiée après la vérification éditoriale.', [{ text: 'Fermer', onPress: () => router.back() }]); } catch { Alert.alert('Envoi impossible', 'Votre contribution n’a pas été envoyée. Vérifiez la connexion puis réessayez.'); }
  }, () => Alert.alert('Informations manquantes', 'Complétez les champs indiqués avant de poursuivre.'));

  return <SafeScreen><ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 40 }} keyboardShouldPersistTaps="handled"><View className="flex-row items-center"><TouchableOpacity onPress={() => router.back()} className="-ml-2 p-2" accessibilityLabel="Retour"><Icon name="chevron-back" size={24} color={colors.text} /></TouchableOpacity><Text className="ml-2 text-2xl font-extrabold" style={{ color: colors.text }}>Transmettre un savoir</Text></View><Text className="mt-2 text-sm" style={{ color: colors.textSecondary }}>Votre contribution est relue avant publication.</Text>{!countryCode ? <Text className="mt-4 text-sm text-[#B91C1C]">Choisissez d’abord votre pays dans vos préférences.</Text> : null}{(!cultureEnabled || !contentPublishingEnabled) ? <Text className="mt-3 text-sm text-[#B91C1C]">La publication culturelle n’est pas disponible pour ce pays.</Text> : null}
    <Label value="Type de contenu" /><View className="flex-row flex-wrap gap-2">{TYPES.map((item) => <TouchableOpacity key={item.value} onPress={() => setValue('type', item.value, { shouldValidate: true })} className="rounded-full px-3 py-2" style={{ backgroundColor: type === item.value ? colors.primary : colors.elevated }}><Text className="text-sm font-semibold" style={{ color: type === item.value ? '#FFFFFF' : colors.text }}>{item.label}</Text></TouchableOpacity>)}</View>
    <Label value="Langue" /><ScrollView horizontal showsHorizontalScrollIndicator={false}>{(languages.data ?? []).map((language) => <TouchableOpacity key={language.code} onPress={() => setValue('primaryLanguageCode', language.code, { shouldValidate: true })} className="mr-2 rounded-full border px-3 py-2" style={{ borderColor: contentLanguage === language.code ? colors.primary : colors.border }}><Text style={{ color: colors.text }}>{language.nativeName}</Text></TouchableOpacity>)}</ScrollView>{errors.primaryLanguageCode ? <Error message={errors.primaryLanguageCode.message} /> : null}
    <FormField control={control} name="title" label="Titre" placeholder={type === 'RECIPE' ? 'Ex. Ndolé aux crevettes' : 'Ex. L’histoire de…'} colors={colors} error={errors.title?.message} /><FormField control={control} name="communityName" label="Communauté (facultatif)" placeholder="Ex. Bassa, Sawa…" colors={colors} /><FormField control={control} name="summary" label="Résumé (facultatif)" placeholder="Quelques lignes pour introduire ce savoir" colors={colors} multiline /><FormField control={control} name="body" label={type === 'RECIPE' ? 'Contexte de la recette' : 'Récit ou explication'} placeholder="Expliquez le contexte, la transmission et vos sources." colors={colors} multiline error={errors.body?.message} />
    {type === 'PROVERB' ? <><FormField control={control} name="literalTranslation" label="Traduction littérale (facultatif)" placeholder="Traduction mot à mot" colors={colors} /><FormField control={control} name="meaning" label="Sens du proverbe" placeholder="Expliquez le sens et le contexte" colors={colors} multiline error={errors.meaning?.message} /><FormField control={control} name="originLanguageCode" label="Code langue d’origine (facultatif)" placeholder="Ex. bas" colors={colors} /><FormField control={control} name="audioUrl" label="URL audio (facultatif)" placeholder="https://…" colors={colors} error={errors.audioUrl?.message} /></> : null}
    {type === 'RECIPE' ? <><Label value="Ingrédients" />{ingredients.fields.map((field, index) => <View key={field.id} className="mb-2 rounded-xl border p-3" style={{ borderColor: colors.border }}><FormField control={control} name={`ingredients.${index}.name`} label="Ingrédient" placeholder="Ex. Feuilles de ndolé" colors={colors} error={errors.ingredients?.[index]?.name?.message} compact /><FormField control={control} name={`ingredients.${index}.quantity`} label="Quantité (facultatif)" placeholder="Ex. 500" colors={colors} compact /><FormField control={control} name={`ingredients.${index}.unit`} label="Unité (facultatif)" placeholder="Ex. g" colors={colors} compact /><TouchableOpacity onPress={() => ingredients.remove(index)}><Text className="mt-2 font-semibold text-[#B91C1C]">Retirer</Text></TouchableOpacity></View>)}<TouchableOpacity onPress={() => ingredients.append({ name: '', quantity: '', unit: '' })} className="self-start rounded-lg border px-3 py-2" style={{ borderColor: colors.primary }}><Text style={{ color: colors.primary }}>Ajouter un ingrédient</Text></TouchableOpacity>{errors.ingredients?.root?.message ? <Error message={errors.ingredients.root.message} /> : null}<Label value="Étapes" />{steps.fields.map((field, index) => <View key={field.id} className="mb-2"><FormField control={control} name={`steps.${index}.instruction`} label={`Étape ${index + 1}`} placeholder="Décrivez cette étape" colors={colors} multiline error={errors.steps?.[index]?.instruction?.message} compact /><TouchableOpacity onPress={() => steps.remove(index)}><Text className="mt-2 font-semibold text-[#B91C1C]">Retirer</Text></TouchableOpacity></View>)}<TouchableOpacity onPress={() => steps.append({ instruction: '' })} className="self-start rounded-lg border px-3 py-2" style={{ borderColor: colors.primary }}><Text style={{ color: colors.primary }}>Ajouter une étape</Text></TouchableOpacity>{errors.steps?.root?.message ? <Error message={errors.steps.root.message} /> : null}</> : null}
    <TouchableOpacity disabled={!countryCode || !contentLanguage || !cultureEnabled || !contentPublishingEnabled || create.isPending || submit.isPending} onPress={() => void publish()} className="mt-7 items-center rounded-xl bg-[#EF4444] p-4" style={{ opacity: countryCode && contentLanguage && cultureEnabled && contentPublishingEnabled ? 1 : 0.5 }}><Text className="font-bold text-white">{create.isPending || submit.isPending ? 'Envoi…' : 'Envoyer pour vérification'}</Text></TouchableOpacity>
  </ScrollView></SafeScreen>;
}
function Label({ value }: { value: string }) { const colors = useThemeStore((state) => state.colors); return <Text className="mb-2 mt-6 text-sm font-bold" style={{ color: colors.text }}>{value}</Text>; }
function Error({ message }: { message?: string }) { return message ? <Text className="mt-1 text-xs text-[#B91C1C]">{message}</Text> : null; }
function FormField({ control, name, label, placeholder, colors, multiline, error, compact }: { control: Control<ContributionValues>; name: FieldPath<ContributionValues>; label: string; placeholder: string; colors: { text: string; textSecondary: string; card: string; border: string }; multiline?: boolean; error?: string; compact?: boolean }) { return <Controller control={control} name={name} render={({ field: { onBlur, onChange, value } }) => <View className={compact ? 'mt-3' : 'mt-5'}><Text className="mb-2 text-sm font-bold" style={{ color: colors.text }}>{label}</Text><TextInput value={typeof value === 'string' ? value : ''} onBlur={onBlur} onChangeText={onChange} multiline={multiline} placeholder={placeholder} placeholderTextColor={colors.textSecondary} className={`rounded-xl border px-4 py-3 ${multiline ? 'min-h-[110px]' : ''}`} style={{ color: colors.text, backgroundColor: colors.card, borderColor: colors.border, textAlignVertical: multiline ? 'top' : 'center' }} /><Error message={error} /></View>} />; }
