import { useState } from 'react';
import { FlatList, Text, TouchableOpacity, View } from 'react-native';
import { useRouter, type Href } from 'expo-router';
import { SafeScreen } from '@/components/ui/SafeScreen';
import { Icon } from '@/components/ui/Icon';
import { FilterChips } from '@/components/partner-dashboard/PartnerPage';
import { TransactionCard } from '@/components/partner-dashboard/finance/TransactionCard';
import { useFinanceSummary, usePartnerTransactions } from '@/features/finance/useFinance';
import { useThemeStore } from '@/features/theme/theme.store';
import type { FinancePeriod } from '@/features/finance/types';
const FILTERS = ['7 jours', '30 jours', '3 mois'] as const;
const VALUE: Record<(typeof FILTERS)[number], FinancePeriod> = { '7 jours': '7D', '30 jours': '30D', '3 mois': '3M' };
export default function FinanceScreen() { const router = useRouter(); const colors = useThemeStore((state) => state.colors); const [filter, setFilter] = useState<(typeof FILTERS)[number]>('30 jours'); const period = VALUE[filter]; const summaryQuery = useFinanceSummary(period); const transactionsQuery = usePartnerTransactions(period); const summary = summaryQuery.data; const refresh = () => { summaryQuery.refetch(); transactionsQuery.refetch(); }; return <SafeScreen><View className="flex-row items-center px-4 pb-2 pt-2"><TouchableOpacity onPress={() => router.back()} className="mr-3 h-10 w-10 items-center justify-center rounded-full" style={{ backgroundColor: colors.elevated }}><Icon name="arrow-back" size={22} color={colors.text} /></TouchableOpacity><View><Text className="text-xl font-extrabold" style={{ color: colors.text }}>Finances</Text><Text className="text-xs" style={{ color: colors.textSecondary }}>Vue financière fournie par YeYamo</Text></View></View><FlatList data={transactionsQuery.data ?? []} keyExtractor={(item) => item.id} renderItem={({ item }) => <TransactionCard transaction={item} onPress={() => router.push(`/(partner-dashboard)/transaction/${item.id}` as Href)} />} contentContainerStyle={{ paddingHorizontal: 16, paddingBottom: 30, flexGrow: 1 }} refreshing={summaryQuery.isRefetching || transactionsQuery.isRefetching} onRefresh={refresh} ListHeaderComponent={<><View className="mt-3 flex-row flex-wrap gap-3"><FinanceCard label="Solde estimé" value={summary?.estimatedBalance} currency={summary?.currency} /><FinanceCard label="Revenus" value={summary?.revenue} currency={summary?.currency} /><FinanceCard label="Commissions YeYamo" value={summary?.yeyamoCommissions} currency={summary?.currency} /><FinanceCard label="Remboursements" value={summary?.refunds} currency={summary?.currency} /></View><FilterChips values={FILTERS} selected={filter} onSelect={(value) => setFilter(value as (typeof FILTERS)[number])} /><Text className="mb-3 mt-3 text-base font-extrabold" style={{ color: colors.text }}>Transactions</Text></>} /></SafeScreen>; }
function FinanceCard({ label, value, currency }: { label: string; value?: number; currency?: string }) { return <View className="w-[48%] rounded-xl bg-[#EF4444] p-4"><Text className="text-xs text-white/80">{label}</Text><Text className="mt-1 text-lg font-extrabold text-white">{value?.toLocaleString('fr-FR') ?? '—'} {currency ?? ''}</Text></View>; }
