import { useState } from 'react';
import { FlatList, Text, TouchableOpacity, View } from 'react-native';
import { type Href, useRouter } from 'expo-router';
import { SafeScreen } from '@/components/ui/SafeScreen';
import { Icon } from '@/components/ui/Icon';
import { FilterChips } from '@/components/partner-dashboard/PartnerPage';
import { TransactionCard } from '@/components/partner-dashboard/finance/TransactionCard';
import { useFinanceSummary, usePartnerTransactions } from '@/features/finance/useFinance';
import { useThemeStore } from '@/features/theme/theme.store';
import type { FinancePeriod } from '@/features/finance/types';
const FILTERS = ['7 jours', '30 jours', '3 mois'] as const;
const VALUE: Record<(typeof FILTERS)[number], FinancePeriod> = { '7 jours': '7D', '30 jours': '30D', '3 mois': '3M' };
export default function FinanceScreen() { const router = useRouter(); const colors = useThemeStore((state) => state.colors); const [filter, setFilter] = useState<(typeof FILTERS)[number]>('30 jours'); const period = VALUE[filter]; const summaryQuery = useFinanceSummary(period); const transactionsQuery = usePartnerTransactions(period); const summary = summaryQuery.data; const transactions = transactionsQuery.data?.pages.flatMap((page) => page.content) ?? []; const forbidden = [summaryQuery.error, transactionsQuery.error].some((error) => typeof error === 'object' && error !== null && 'response' in error && (error as { response?: { status?: number } }).response?.status === 403); const refresh = () => { summaryQuery.refetch(); transactionsQuery.refetch(); }; return <SafeScreen><View className="flex-row items-center px-4 pb-2 pt-2"><TouchableOpacity onPress={() => router.back()} className="mr-3 h-10 w-10 items-center justify-center rounded-full" style={{ backgroundColor: colors.elevated }}><Icon name="arrow-back" size={22} color={colors.text} /></TouchableOpacity><View><Text className="text-xl font-extrabold" style={{ color: colors.text }}>Finances</Text><Text className="text-xs" style={{ color: colors.textSecondary }}>Données XAF issues du ledger YeYamo</Text></View></View><FlatList data={transactions} keyExtractor={(item) => item.id} renderItem={({ item }) => <TransactionCard transaction={item} onPress={() => router.push(`/(partner-dashboard)/transaction/${item.id}` as Href)} />} contentContainerStyle={{ paddingHorizontal: 16, paddingBottom: 30, flexGrow: 1 }} refreshing={summaryQuery.isRefetching || transactionsQuery.isRefetching} onRefresh={refresh} onEndReached={() => { if (transactionsQuery.hasNextPage && !transactionsQuery.isFetchingNextPage) transactionsQuery.fetchNextPage(); }} onEndReachedThreshold={0.4} ListHeaderComponent={<><View className="mt-3 flex-row flex-wrap gap-3"><FinanceCard label="Solde" value={summary?.balance} currency={summary?.currency} /><FinanceCard label="Revenus bruts" value={summary?.grossRevenue} currency={summary?.currency} /><FinanceCard label="Commissions YeYamo" value={summary?.commissions} currency={summary?.currency} /><FinanceCard label="Remboursements" value={summary?.refunds} currency={summary?.currency} /></View><FilterChips values={FILTERS} selected={filter} onSelect={(value) => setFilter(value as (typeof FILTERS)[number])} /><Text className="mb-3 mt-3 text-base font-extrabold" style={{ color: colors.text }}>Transactions</Text></>} ListEmptyComponent={<View className="items-center py-16"><Icon name={forbidden ? 'lock-closed-outline' : 'receipt-outline'} size={36} color={colors.textMuted} /><Text className="mt-3 font-semibold" style={{ color: colors.text }}>{forbidden ? 'Accès financier non autorisé' : 'Aucune transaction'}</Text></View>} /></SafeScreen>; }
function FinanceCard({ label, value, currency }: { label: string; value?: number; currency?: string }) { const colors = useThemeStore((state) => state.colors); return <View className="w-[47%] rounded-2xl border p-4" style={{ backgroundColor: colors.card, borderColor: colors.border }}><Text className="text-xs" style={{ color: colors.textSecondary }}>{label}</Text><Text className="mt-2 text-xl font-extrabold" style={{ color: colors.text }}>{value?.toLocaleString('fr-FR') ?? '—'} {currency ?? ''}</Text></View>; }
