import type { Experience } from './types';

export const mockExperiences: Experience[] = [
  {
    id: 1,
    title: 'Randonnée Mont Cameroun',
    description: 'Une aventure inoubliable jusqu\'au sommet du Mont Cameroun, le plus haut sommet d\'Afrique de l\'Ouest. Découvrez des paysages à couper le souffle, une faune unique et vivez une expérience de trekking mémorable.',
    location: 'Buéa, Sud-Ouest',
    city: 'Buéa',
    region: 'Sud-Ouest',
    cover_image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    ],
    rating: 4.8,
    reviews_count: 156,
    price_from: 85000,
    currency: 'FCFA',
    duration_hours: 8,
    duration_days: 2,
    difficulty: 'difficile',
    group_size_min: 4,
    group_size_max: 12,
    languages: ['Français', 'Anglais'],
    availability: 'available',
    category: 'adventure',
    included_items: [
      { id: '1', label: 'Guide', icon: 'person', iconLibrary: 'ionicons' },
      { id: '2', label: 'Transport', icon: 'car', iconLibrary: 'ionicons' },
      { id: '3', label: 'Repas', icon: 'restaurant', iconLibrary: 'ionicons' },
      { id: '4', label: 'Hébergement', icon: 'bed', iconLibrary: 'ionicons' },
    ],
    equipment_provided: ['Tente', 'Sac de couchage', 'Bâtons de randonnée', 'Casque'],
    is_saved: false,
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 2,
    title: 'Découverte de Kribi',
    description: 'Explorez les magnifiques plages de Kribi et les chutes de la Lobé. Une expérience unique au bord de l\'océan Atlantique.',
    location: 'Kribi, Sud',
    city: 'Kribi',
    region: 'Sud',
    cover_image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    ],
    rating: 4.7,
    reviews_count: 203,
    price_from: 45000,
    currency: 'FCFA',
    duration_hours: 6,
    difficulty: 'facile',
    group_size_min: 2,
    group_size_max: 20,
    languages: ['Français'],
    availability: 'available',
    category: 'nature',
    included_items: [
      { id: '1', label: 'Guide', icon: 'person', iconLibrary: 'ionicons' },
      { id: '2', label: 'Transport', icon: 'car', iconLibrary: 'ionicons' },
      { id: '3', label: 'Repas', icon: 'restaurant', iconLibrary: 'ionicons' },
    ],
    equipment_provided: ['Gilet de sauvetage'],
    is_saved: false,
    created_at: '2024-02-10T14:00:00Z',
  },
  {
    id: 3,
    title: 'Extension Lac Nyos',
    description: 'Visitez le mystérieux lac Nyos et découvrez son histoire fascinante.',
    location: 'Nyos, Nord-Ouest',
    city: 'Nyos',
    region: 'Nord-Ouest',
    cover_image_url: 'https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=800',
    images: [
      'https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=800',
    ],
    rating: 4.6,
    reviews_count: 89,
    price_from: 65000,
    currency: 'FCFA',
    duration_hours: 10,
    duration_days: 1,
    difficulty: 'modérée',
    group_size_min: 3,
    group_size_max: 15,
    languages: ['Français', 'Anglais'],
    availability: 'limited',
    category: 'nature',
    included_items: [
      { id: '1', label: 'Guide', icon: 'person', iconLibrary: 'ionicons' },
      { id: '2', label: 'Transport', icon: 'car', iconLibrary: 'ionicons' },
    ],
    equipment_provided: ['Jumelles'],
    is_saved: true,
    created_at: '2024-01-20T09:00:00Z',
  },
];
