import type { Experience } from './types';

export const mockExperiences: Experience[] = [
  {
    id: 1,
    title: 'Randonnée Mont Cameroun',
    description: 'Explorez une mystérieuse aventure avec des guides expérimentés. Une aventure inoubliable jusqu\'au sommet du Mont Cameroun, le plus haut sommet d\'Afrique de l\'Ouest. Découvrez des paysages à couper le souffle, une faune unique et vivez une expérience de trekking mémorable.',
    location: 'Buéa',
    city: 'Buéa',
    region: 'Sud-Ouest',
    cover_image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    ],
    rating: 4.8,
    reviews_count: 72,
    price_from: 85000,
    currency: 'FCFA',
    duration_hours: 8,
    duration_days: 2,
    difficulty: 'difficile',
    difficulty_label: 'Modérée',
    distance_km: 15,
    required_deposit: 30000,
    group_size_min: 4,
    group_size_max: 12,
    languages: ['Français', 'Anglais'],
    availability: 'available',
    category: 'adventure',
    included_items: [
      { id: '1', label: 'Guide', icon: 'person', iconLibrary: 'ionicons' },
      { id: '2', label: 'Transport', icon: 'car', iconLibrary: 'ionicons' },
      { id: '3', label: 'Repas', icon: 'restaurant', iconLibrary: 'ionicons' },
      { id: '4', label: 'Hébergement', icon: 'bed', iconLibrary: 'ionicons' },
    ],
    equipment_provided: ['Tente', 'Sac de couchage', 'Bâtons de randonnée'],
    highlights: [
      { id: '1', icon: 'checkmark-circle', label: 'Vue panoramique du sommet' },
      { id: '2', icon: 'checkmark-circle', label: 'Accompagnement par guide certifié' },
      { id: '3', icon: 'checkmark-circle', label: 'Hébergement en refuge de montagne' },
    ],
    reviews: [
      {
        id: '1',
        user_name: 'Alicia M.',
        user_avatar: 'https://i.pravatar.cc/150?img=9',
        rating: 5,
        comment: 'Expérience inoubliable ! Le guide était super et la vue au sommet valait tous les efforts.',
        date: 'Il y a 1 semaine',
      },
    ],
    is_saved: false,
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 2,
    title: 'Découverte de Kribi',
    description: 'Explorez les magnifiques plages de Kribi et les chutes de la Lobé.',
    location: 'Kribi',
    city: 'Kribi',
    region: 'Sud',
    cover_image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
    rating: 4.7,
    reviews_count: 203,
    price_from: 45000,
    currency: 'FCFA',
    duration_hours: 6,
    difficulty: 'facile',
    group_size_min: 2,
    group_size_max: 20,
    languages: ['Français'],
    availability: 'available',
    category: 'nature',
    included_items: [
      { id: '1', label: 'Guide', icon: 'person', iconLibrary: 'ionicons' },
      { id: '2', label: 'Transport', icon: 'car', iconLibrary: 'ionicons' },
    ],
    equipment_provided: ['Gilet de sauvetage'],
    is_saved: false,
    created_at: '2024-02-10T14:00:00Z',
  },
];
