import type { Artisan } from './artisans.types';
const specialty = (id: string, code: string, name: string) => ({ id, code, name, description: null });
const base = { countryCode: 'CM', localityId: null, acceptsCustomOrders: true, verificationStatus: 'VERIFIED', featured: true, createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-08-01T00:00:00Z' } as const;
export const demoArtisans: Artisan[] = [
  { ...base, partnerId: 'demo-artisan-1', displayName: 'Atelier Nguon', story: 'Trois générations de sculpteurs réunies dans un atelier familial.', craftDescription: 'Sculpture sur bois et masques de transmission.', yearsOfExperience: 18, adminLevel1Id: 'OUEST', cityId: 'Foumban', languages: ['fr', 'bamoun'], specialties: [specialty('sp-1', 'SCULPTURE', 'Sculpture')], internationalShipping: true, avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400', coverImageUrl: 'https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=900' },
  { ...base, partnerId: 'demo-artisan-2', displayName: 'Poteries de Mami Wouri', story: 'Une pratique de la terre héritée des femmes Sawa.', craftDescription: 'Poteries culinaires et décoratives façonnées à la main.', yearsOfExperience: 24, adminLevel1Id: 'LITTORAL', cityId: 'Douala', languages: ['fr', 'douala'], specialties: [specialty('sp-2', 'POTTERY', 'Poterie')], internationalShipping: false, avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400', coverImageUrl: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=900' },
  { ...base, partnerId: 'demo-artisan-3', displayName: 'Tissages Bamenda', story: 'Des motifs qui racontent les chefferies des Grassfields.', craftDescription: 'Tissage traditionnel, étoffes et accessoires contemporains.', yearsOfExperience: 12, adminLevel1Id: 'NORD-OUEST', cityId: 'Bamenda', languages: ['en', 'pidgin'], specialties: [specialty('sp-3', 'WEAVING', 'Tissage')], internationalShipping: true, avatarUrl: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400', coverImageUrl: 'https://images.unsplash.com/photo-1606722590583-6951b5ea92ad?w=900' },
  { ...base, partnerId: 'demo-artisan-4', displayName: 'Bijoux du Sahel', story: 'Le métal travaillé au rythme des marchés du Nord.', craftDescription: 'Bijoux en laiton, argent et perles recyclées.', yearsOfExperience: 16, adminLevel1Id: 'NORD', cityId: 'Garoua', languages: ['fr', 'fulfulde'], specialties: [specialty('sp-4', 'JEWELRY', 'Bijouterie')], internationalShipping: true, avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400', coverImageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=900' },
  { ...base, partnerId: 'demo-artisan-5', displayName: 'Vannerie de Kribi', story: 'Des fibres locales transformées près de l’océan.', craftDescription: 'Paniers, luminaires et objets en raphia.', yearsOfExperience: 9, adminLevel1Id: 'SUD', cityId: 'Kribi', languages: ['fr', 'bulu'], specialties: [specialty('sp-5', 'BASKETRY', 'Vannerie')], internationalShipping: false, avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', coverImageUrl: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=900' },
  { ...base, partnerId: 'demo-artisan-6', displayName: 'Cuir de Maroua', story: 'Un atelier collectif formant de jeunes maroquiniers.', craftDescription: 'Sacs, sandales et accessoires en cuir tanné localement.', yearsOfExperience: 20, adminLevel1Id: 'EXTREME-NORD', cityId: 'Maroua', languages: ['fr', 'fulfulde'], specialties: [specialty('sp-6', 'LEATHER', 'Maroquinerie')], internationalShipping: true, avatarUrl: 'https://images.unsplash.com/photo-1521119989659-a83eee488004?w=400', coverImageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=900' },
];
export const demoArtisan = demoArtisans[0];
