import { Alert, ScrollView, Share, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { CollectionPlaceItem } from '@/components/collections/CollectionPlaceItem';
import { Button } from '@/components/ui/Button';
import { EmptyState, ErrorState, LoadingState } from '@/components/ui/ViewStates';
import { SafeScreen } from '@/components/ui/SafeScreen';
import { useCollection, useDeleteCollection, useUpdatePlaceInCollection } from '@/features/collections/useCollections';
import type { EntityId } from '@/types/api.types';
import { useThemeStore } from '@/features/theme/theme.store';

export default function CollectionDetailScreen() {
  const router = useRouter(); const colors = useThemeStore((state) => state.colors); const { id } = useLocalSearchParams<{ id: string }>(); const collectionId = id ?? '';
  const query = useCollection(collectionId); const remove = useDeleteCollection(); const updatePlace = useUpdatePlaceInCollection();
  if (query.isLoading) return <LoadingState label="Chargement de la collection…" />;
  if (query.isError || !query.data) return <ErrorState title="Collection indisponible" retry={() => void query.refetch()} />;
  const collection = query.data;
  const share = () => void Share.share({ message: `${collection.name} · ${collection.places_count} lieu${collection.places_count > 1 ? 'x' : ''} sur Yeyamo` });
  const deleteCollection = () => Alert.alert('Supprimer la collection', 'Cette collection sera supprimée du serveur.', [{ text: 'Annuler', style: 'cancel' }, { text: 'Supprimer', style: 'destructive', onPress: () => remove.mutate(collectionId, { onSuccess: () => router.back() }) }]);
  const togglePriority = (placeId: EntityId, isPriority: boolean, note?: string) => updatePlace.mutate({ collectionId, placeId, isPriority: !isPriority, note });
  return <SafeScreen><View className="flex-row items-center border-b px-4 py-3" style={{ borderColor: colors.border }}><TouchableOpacity onPress={() => router.back()} className="-ml-2 p-2" accessibilityRole="button" accessibilityLabel="Retour"><Ionicons name="chevron-back" size={24} color={colors.text} /></TouchableOpacity><Text className="ml-2 flex-1 text-xl font-bold" style={{ color: colors.text }} numberOfLines={1}>{collection.name}</Text><TouchableOpacity onPress={deleteCollection} disabled={remove.isPending} className="p-2" accessibilityRole="button" accessibilityLabel="Supprimer la collection"><Ionicons name="trash-outline" size={21} color={colors.primary} /></TouchableOpacity></View><ScrollView contentContainerStyle={{ paddingBottom: 32 }}><View className="h-44 items-center justify-center" style={{ backgroundColor: colors.elevated }}><Ionicons name="images-outline" size={58} color={colors.textMuted} /><Text className="mt-2 text-sm" style={{ color: colors.textSecondary }}>Aucune couverture disponible</Text></View><View className="border-b p-4" style={{ borderColor: colors.border }}><View className="flex-row items-center"><Text className="flex-1 text-2xl font-extrabold" style={{ color: colors.text }}>{collection.name}</Text><Ionicons name={collection.visibility === 'public' ? 'earth-outline' : 'lock-closed-outline'} size={18} color={colors.textMuted} /></View><Text className="mt-1 text-sm" style={{ color: colors.textSecondary }}>{collection.places_count} {collection.places_count > 1 ? 'lieux' : 'lieu'} · {collection.visibility === 'public' ? 'Publique' : 'Privée'}</Text>{collection.description ? <Text className="mt-3 leading-6" style={{ color: colors.textSecondary }}>{collection.description}</Text> : null}<View className="mt-4 flex-row gap-3"><View className="flex-1"><Button label="Partager" variant="secondary" onPress={share} /></View><View className="flex-1"><Button label="Ajouter un lieu" onPress={() => router.push('/(explore)/places')} /></View></View>{updatePlace.isError ? <Text className="mt-3 text-xs" style={{ color: colors.primary }}>La priorité du lieu n’a pas pu être mise à jour.</Text> : null}</View><View className="p-4">{collection.places.length ? collection.places.map((place) => <CollectionPlaceItem key={place.id} place={place} onPress={() => router.push(`/(places)/${place.id}`)} onTogglePriority={() => togglePriority(place.id, Boolean(place.is_priority), place.note)} />) : <View className="h-56"><EmptyState title="Aucun lieu" message="Ajoutez des lieux pour les retrouver dans cette collection." icon={<Ionicons name="location-outline" size={54} color={colors.textMuted} />} /></View>}</View></ScrollView></SafeScreen>;
}
