import { useState } from 'react';
import { FlatList, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { CollectionCard } from '@/components/collections/CollectionCard';
import { Button } from '@/components/ui/Button';
import { EmptyState, ErrorState, LoadingState } from '@/components/ui/ViewStates';
import { SafeScreen } from '@/components/ui/SafeScreen';
import { usePublicCollections, useUserCollections } from '@/features/collections/useCollections';
import type { CollectionTab } from '@/features/collections/types';
import { useThemeStore } from '@/features/theme/theme.store';

export default function CollectionsScreen() {
  const router = useRouter(); const colors = useThemeStore((state) => state.colors); const [tab, setTab] = useState<CollectionTab>('saved');
  const own = useUserCollections(); const publicCollections = usePublicCollections(); const current = tab === 'saved' ? own : publicCollections;
  return <SafeScreen><View className="flex-row items-center justify-between border-b px-4 py-3" style={{ borderColor: colors.border }}><TouchableOpacity onPress={() => router.canGoBack() ? router.back() : router.replace('/(tabs)/profile')} className="-ml-2 p-2" accessibilityRole="button" accessibilityLabel="Retour"><Ionicons name="chevron-back" size={24} color={colors.text} /></TouchableOpacity><Text className="text-xl font-bold" style={{ color: colors.text }}>Mes collections</Text><TouchableOpacity onPress={() => router.push('/(collections)/create')} className="p-2" accessibilityRole="button" accessibilityLabel="Créer une collection"><Ionicons name="add" size={28} color={colors.text} /></TouchableOpacity></View><View className="flex-row border-b px-4 pt-4" style={{ borderColor: colors.border }}><Tab label="Enregistrées" active={tab === 'saved'} onPress={() => setTab('saved')} /><Tab label="Collections publiques" active={tab === 'public'} onPress={() => setTab('public')} /></View>{current.isLoading ? <LoadingState label="Chargement des collections…" /> : current.isError ? <ErrorState title="Collections indisponibles" retry={() => void current.refetch()} /> : current.data?.length ? <FlatList data={current.data} keyExtractor={(item) => String(item.id)} numColumns={2} contentContainerStyle={{ padding: 16 }} columnWrapperStyle={{ gap: 12 }} ItemSeparatorComponent={() => <View className="h-3" />} renderItem={({ item }) => <View className="flex-1"><CollectionCard collection={item} onPress={() => router.push(`/(collections)/${item.id}`)} /></View>} /> : <View className="flex-1"><EmptyState title={tab === 'saved' ? 'Aucune collection' : 'Aucune collection publique'} message={tab === 'saved' ? 'Créez une collection pour organiser vos lieux.' : 'Les collections publiques apparaîtront ici.'} icon={<Ionicons name="albums-outline" size={64} color={colors.textMuted} />} />{tab === 'saved' ? <View className="absolute bottom-8 left-4 right-4"><Button label="Créer une collection" onPress={() => router.push('/(collections)/create')} /></View> : null}</View>}</SafeScreen>;
}
function Tab({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { const colors = useThemeStore((state) => state.colors); return <TouchableOpacity onPress={onPress} className="flex-1 border-b-2 pb-3" style={{ borderColor: active ? colors.primary : 'transparent' }} accessibilityRole="tab" accessibilityState={{ selected: active }}><Text className="text-center font-semibold" style={{ color: active ? colors.primary : colors.textSecondary }}>{label}</Text></TouchableOpacity>; }
