import { ScrollView, Switch, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { SafeScreen } from '@/components/ui/SafeScreen';
import { ErrorState, LoadingState } from '@/components/ui/ViewStates';
import { useSocialSettings, useUpdateSocialSettings } from '@/features/social/useSocial';
import type { SocialSettings } from '@/features/social/types';
import { useThemeStore } from '@/features/theme/theme.store';

export default function PrivacyScreen() {
  const router = useRouter(); const colors = useThemeStore((state) => state.colors); const settings = useSocialSettings(); const update = useUpdateSocialSettings();
  if (settings.isLoading) return <LoadingState label="Chargement des réglages…" />;
  if (settings.isError || !settings.data) return <ErrorState title="Réglages indisponibles" message="La confidentialité ne peut pas être chargée." retry={() => void settings.refetch()} />;
  const privacy = settings.data.privacy;
  const mutate = (patch: Partial<SocialSettings['privacy']>) => update.mutate({ privacy: { ...privacy, ...patch } });
  return <SafeScreen><Header onBack={() => router.back()} /><ScrollView contentContainerStyle={{ paddingBottom: 32 }}><Section title="Visibilité du profil"><Card>{([['public', 'Public', 'Tout le monde peut voir votre profil'], ['followers', 'Abonnés uniquement', 'Seuls vos abonnés peuvent voir votre profil'], ['private', 'Privé', 'Votre profil est privé']] as const).map(([value, label, description]) => <TouchableOpacity key={value} disabled={update.isPending} onPress={() => mutate({ profile_visibility: value })} className="flex-row items-center border-t p-4 first:border-t-0" style={{ borderColor: colors.border }} accessibilityRole="radio" accessibilityState={{ selected: privacy.profile_visibility === value }}><View className="flex-1"><Text className="font-semibold" style={{ color: colors.text }}>{label}</Text><Text className="mt-1 text-xs" style={{ color: colors.textSecondary }}>{description}</Text></View><Ionicons name={privacy.profile_visibility === value ? 'radio-button-on' : 'radio-button-off'} size={22} color={privacy.profile_visibility === value ? colors.primary : colors.textMuted} /></TouchableOpacity>)}</Card></Section><Section title="Réseau social"><Card><SwitchRow label="Afficher mon activité" description="Autorise l’affichage de votre activité sociale." value={privacy.show_activity} onChange={(show_activity) => mutate({ show_activity })} disabled={update.isPending} /><SwitchRow label="Afficher mes abonnés" description="Autorise l’affichage de votre liste d’abonnés." value={privacy.show_followers} onChange={(show_followers) => mutate({ show_followers })} disabled={update.isPending} /><SwitchRow label="Afficher mes abonnements" description="Autorise l’affichage de vos abonnements." value={privacy.show_following} onChange={(show_following) => mutate({ show_following })} disabled={update.isPending} /></Card></Section>{update.isError ? <Text className="mx-4 mt-4 text-sm" style={{ color: colors.primary }}>La modification a échoué et la valeur précédente a été restaurée.</Text> : null}<Text className="mx-4 mt-5 text-xs leading-5" style={{ color: colors.textSecondary }}>Les réglages de messages, tags, localisation et statut en ligne ne sont pas affichés car ils ne sont pas fournis par le contrat backend actuel.</Text></ScrollView></SafeScreen>;
}
function Header({ onBack }: { onBack: () => void }) { const colors = useThemeStore((state) => state.colors); return <View className="flex-row items-center border-b px-4 py-3" style={{ borderColor: colors.border }}><TouchableOpacity onPress={onBack} className="-ml-2 p-2"><Ionicons name="chevron-back" size={24} color={colors.text} /></TouchableOpacity><Text className="ml-2 text-xl font-bold" style={{ color: colors.text }}>Confidentialité</Text></View>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { const colors = useThemeStore((state) => state.colors); return <View className="mt-6 px-4"><Text className="mb-3 text-xs font-semibold uppercase" style={{ color: colors.textSecondary }}>{title}</Text>{children}</View>; }
function Card({ children }: { children: React.ReactNode }) { const colors = useThemeStore((state) => state.colors); return <View className="overflow-hidden rounded-xl" style={{ backgroundColor: colors.surface }}>{children}</View>; }
function SwitchRow({ label, description, value, onChange, disabled }: { label: string; description: string; value: boolean; onChange: (value: boolean) => void; disabled: boolean }) { const colors = useThemeStore((state) => state.colors); return <View className="flex-row items-center border-t p-4 first:border-t-0" style={{ borderColor: colors.border }}><View className="flex-1 pr-3"><Text className="font-semibold" style={{ color: colors.text }}>{label}</Text><Text className="mt-1 text-xs" style={{ color: colors.textSecondary }}>{description}</Text></View><Switch value={value} disabled={disabled} onValueChange={onChange} trackColor={{ false: colors.border, true: colors.primary }} thumbColor="#FFFFFF" /></View>; }
