import { useState } from 'react';
import { FlatList, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { ReservationCard } from '@/components/profile/ReservationCard';
import { EmptyState, ErrorState, LoadingState } from '@/components/ui/ViewStates';
import { SafeScreen } from '@/components/ui/SafeScreen';
import { useCancelUserReservation, useUserReservations } from '@/features/profile/useProfile';
import { useThemeStore } from '@/features/theme/theme.store';
import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';

export default function ReservationsScreen() {
  const router = useRouter(); const colors = useThemeStore((state) => state.colors); const [activeTab, setActiveTab] = useState<'confirmed' | 'pending'>('confirmed'); const [cancellingId, setCancellingId] = useState<string | null>(null); const [cancellationReason, setCancellationReason] = useState(''); const query = useUserReservations(); const cancel = useCancelUserReservation(); const filtered = query.data?.filter((reservation) => reservation.status === activeTab || (activeTab === 'confirmed' && reservation.status === 'confirmed'));
  const confirmCancellation = () => { if (!cancellingId || !cancellationReason.trim()) return; cancel.mutate({ id: cancellingId, reason: cancellationReason.trim() }, { onSuccess: () => { setCancellingId(null); setCancellationReason(''); } }); };
  const cancellationForm = cancellingId ? <View className="mx-4 mb-3 rounded-xl border p-4" style={{ backgroundColor: colors.card, borderColor: colors.border }}><Text className="text-sm font-bold" style={{ color: colors.text }}>Motif d’annulation</Text><Input value={cancellationReason} onChangeText={setCancellationReason} placeholder="Indiquez le motif demandé par le service de réservation" multiline containerClassName="mt-3" error={cancel.isError ? 'L’annulation a échoué. Réessayez.' : undefined} /><View className="mt-3 flex-row justify-end gap-2"><Button label="Fermer" variant="secondary" onPress={() => { setCancellingId(null); setCancellationReason(''); }} /><Button label="Confirmer" disabled={!cancellationReason.trim()} isLoading={cancel.isPending} onPress={confirmCancellation} /></View></View> : null;
  return <SafeScreen><Header title="Mes réservations" onBack={() => router.back()} /><View className="flex-row border-b px-4 pt-4" style={{ borderColor: colors.border }}><Tab label="Confirmées" active={activeTab === 'confirmed'} onPress={() => setActiveTab('confirmed')} /><Tab label="En attente" active={activeTab === 'pending'} onPress={() => setActiveTab('pending')} /></View>{cancellationForm}{query.isLoading ? <LoadingState label="Chargement de vos réservations…" /> : query.isError ? <ErrorState title="Impossible de charger les réservations" message="Vérifiez votre connexion puis réessayez." retry={() => void query.refetch()} /> : filtered?.length ? <FlatList data={filtered} keyExtractor={(item) => item.id.toString()} contentContainerStyle={{ padding: 16 }} refreshing={query.isRefetching} onRefresh={() => void query.refetch()} renderItem={({ item }) => <ReservationCard reservation={item} onRequestCancellation={() => { setCancellingId(String(item.id)); setCancellationReason(''); }} />} /> : <EmptyState title={activeTab === 'confirmed' ? 'Aucune réservation confirmée' : 'Aucune réservation en attente'} message="Vos réservations apparaîtront ici." icon={<Ionicons name="calendar-outline" size={64} color={colors.textMuted} />} />}</SafeScreen>;
}

function Header({ title, onBack }: { title: string; onBack: () => void }) { const colors = useThemeStore((state) => state.colors); return <View className="flex-row items-center justify-between border-b px-4 py-3" style={{ borderColor: colors.border }}><TouchableOpacity onPress={onBack} className="-ml-2 p-2" accessibilityRole="button" accessibilityLabel="Retour"><Ionicons name="chevron-back" size={24} color={colors.text} /></TouchableOpacity><Text className="text-xl font-bold" style={{ color: colors.text }}>{title}</Text><View className="w-10" /></View>; }
function Tab({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { const colors = useThemeStore((state) => state.colors); return <TouchableOpacity onPress={onPress} className="flex-1 border-b-2 pb-3" style={{ borderColor: active ? colors.primary : 'transparent' }} accessibilityRole="tab" accessibilityState={{ selected: active }}><Text className="text-center font-semibold" style={{ color: active ? colors.primary : colors.textSecondary }}>{label}</Text></TouchableOpacity>; }
