import { useEffect, useState } from 'react';
import { ScrollView, Switch, Text, TouchableOpacity, View } from 'react-native';
import { Icon } from '@/components/ui/Icon';
import { LoadingState } from '@/components/ui/ViewStates';
import { useSocialSettings, useUpdateSocialSettings } from '@/features/social/useSocial';
import type { SocialSettings } from '@/features/social/types';
import { useThemeStore } from '@/features/theme/theme.store';

export default function SocialSettingsScreen() {
  const { data } = useSocialSettings(); const updateSettings = useUpdateSocialSettings(); const colors = useThemeStore((state) => state.colors); const [settings, setSettings] = useState<SocialSettings | null>(null);
  useEffect(() => { if (data) setSettings(data); }, [data]);
  const updatePrivacy = <Key extends keyof SocialSettings['privacy']>(key: Key, value: SocialSettings['privacy'][Key]) => { if (!settings) return; const next = { ...settings, privacy: { ...settings.privacy, [key]: value } }; setSettings(next); updateSettings.mutate({ privacy: next.privacy }); };
  const updateNotifications = (key: keyof SocialSettings['notifications'], value: boolean) => { if (!settings) return; const next = { ...settings, notifications: { ...settings.notifications, [key]: value } }; setSettings(next); updateSettings.mutate({ notifications: next.notifications }); };
  const updatePreferences = (key: keyof SocialSettings['preferences'], value: boolean) => { if (!settings) return; const next = { ...settings, preferences: { ...settings.preferences, [key]: value } }; setSettings(next); updateSettings.mutate({ preferences: next.preferences }); };
  if (!settings) return <View className="flex-1" style={{ backgroundColor: colors.background }}><LoadingState /></View>;
  const cycleVisibility = () => { const values: SocialSettings['privacy']['profile_visibility'][] = ['public', 'followers', 'private']; const position = values.indexOf(settings.privacy.profile_visibility); updatePrivacy('profile_visibility', values[(position + 1) % values.length]); };
  const visibility = settings.privacy.profile_visibility === 'public' ? 'Public — Tout le monde' : settings.privacy.profile_visibility === 'followers' ? 'Abonnés uniquement' : 'Privé';
  return <View className="flex-1" style={{ backgroundColor: colors.background }}><ScrollView contentContainerStyle={{ paddingBottom: 32 }}><SettingsSection title="Confidentialité"><SettingsLink label="Visibilité du profil" description={visibility} onPress={cycleVisibility} /><SettingsSwitch label="Afficher mon activité" description="Les autres peuvent voir vos likes et commentaires" value={settings.privacy.show_activity} onChange={(value) => updatePrivacy('show_activity', value)} /><SettingsSwitch label="Afficher mes abonnés" description="Masquer votre liste d’abonnés" value={settings.privacy.show_followers} onChange={(value) => updatePrivacy('show_followers', value)} /><SettingsSwitch label="Afficher mes abonnements" description="Masquer votre liste d’abonnements" value={settings.privacy.show_following} onChange={(value) => updatePrivacy('show_following', value)} /></SettingsSection><SettingsSection title="Notifications"><SettingsSwitch label="Nouveaux abonnés" description="Quand quelqu’un vous suit" value={settings.notifications.new_followers} onChange={(value) => updateNotifications('new_followers', value)} /><SettingsSwitch label="Demandes d’abonnement" description="Si votre profil est privé" value={settings.notifications.follow_requests} onChange={(value) => updateNotifications('follow_requests', value)} /><SettingsSwitch label="Mentions" description="Quand quelqu’un vous mentionne" value={settings.notifications.mentions} onChange={(value) => updateNotifications('mentions', value)} /><SettingsSwitch label="Mises à jour d’activité" description="Activité de votre réseau" value={settings.notifications.activity_updates} onChange={(value) => updateNotifications('activity_updates', value)} /></SettingsSection><SettingsSection title="Préférences"><SettingsSwitch label="Autoriser les suggestions" description="Suggérer votre profil aux autres" value={settings.preferences.allow_suggestions} onChange={(value) => updatePreferences('allow_suggestions', value)} /><SettingsSwitch label="Messages des inconnus" description="Autoriser les personnes que vous ne suivez pas" value={settings.preferences.allow_messages_from_strangers} onChange={(value) => updatePreferences('allow_messages_from_strangers', value)} /></SettingsSection></ScrollView></View>;
}

function SettingsSection({ title, children }: { title: string; children: React.ReactNode }) { const colors = useThemeStore((state) => state.colors); return <View className="mt-6"><Text className="mb-3 px-4 text-base font-bold" style={{ color: colors.text }}>{title}</Text><View className="mx-4 overflow-hidden rounded-xl" style={{ backgroundColor: colors.surface }}>{children}</View></View>; }
function SettingsLink({ label, description, onPress }: { label: string; description: string; onPress: () => void }) { const colors = useThemeStore((state) => state.colors); return <TouchableOpacity onPress={onPress} className="flex-row items-center justify-between p-4" accessibilityRole="button"><View className="flex-1"><Text className="text-sm font-semibold" style={{ color: colors.text }}>{label}</Text><Text className="mt-1 text-xs" style={{ color: colors.textSecondary }}>{description}</Text></View><Icon library="ionicons" name="chevron-forward" size={20} color={colors.textMuted} /></TouchableOpacity>; }
function SettingsSwitch({ label, description, value, onChange }: { label: string; description: string; value: boolean; onChange: (value: boolean) => void }) { const colors = useThemeStore((state) => state.colors); return <View className="flex-row items-center justify-between border-t p-4" style={{ borderColor: colors.border }}><View className="flex-1 pr-4"><Text className="text-sm font-semibold" style={{ color: colors.text }}>{label}</Text><Text className="mt-1 text-xs" style={{ color: colors.textSecondary }}>{description}</Text></View><Switch value={value} onValueChange={onChange} trackColor={{ false: colors.border, true: colors.primary }} thumbColor="#FFFFFF" /></View>; }
